### ISSUE TITLE
AVIHL Algoritmasının oluşturulması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#114]

**Comment by boratuncer** [comment]
long için açılmış bir sinyalde tek "Min - Standard Dev." en yüksek rakamı "Max + Standard Dev."  rakamı ile kesişirse kapatılacak, aynı şekilde short için açılmış bir sinyalde tek "Max + Standard Dev." en düşük rakamı "Min - Standard Dev." ile kapatacak

**Comment by boratuncer** [comment]
Short için MinOf(Max + Stddev) < (Min - Stddev)
Long için MaxOf(Min - Stddev) > (Max + Stddev)

**Comment by erkannurel** [comment]
Eğer Short için MinOf(Max + Stddev) < (Min - Stddev) veya Long için MaxOf(Min - Stddev) > (Max + Stddev) durumu olmamış ise ve ALAL olşuyorsa tekrar terse pozisyon aç. 

Toplam hacim yarı yarıya azalmış olsa bile tekrar terse pozisyon açma...

Açılan pozisyon SL yemiş ise terse pozisyon açma...

Güvenlik amaçlı BELKİ sabit bir SL koyabiliriz. Örneğin, short pozisyonu açtık bir süre sonra S&P Türkiye'nin kredi notunu arttırdı ve piyasa birden Long'a döndü. Böyle beklenmeyen bir durumda sabit SL kapatsın diyebiliriz. Sert hareketler bizim adaptive TP/SL sistemimize erken cevap veremiyor. 

Bu oluşturduğumuz bantların en güzel yanı istediğimiz algoritmaya adaptive TP/SL olarak implemente edebiliriz.

**Comment by boratuncer** [comment]
Algoritma bu haliyle eklendi.
