### ISSUE TITLE
Error dosyasındaki hata

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#115]
Aşağıdaki hatanın ne olduğunu anlayamadım. Program çalışırken bir problem yok gözüküyor. 

18:15:17 VIOPLink.CallBackHTTPPost()
18:15:17 Object reference not set to an instance of an object.
18:15:17    at VOB_ALGO.Engine.VIOPLink.CallBackHTTPPost(Boolean status, String command, String result) in C:\MyProjects\Home\VOB ALGO\VOB ALGO\VOB ALGO\Engine\VIOPLink.cs:line 114
18:15:17 VIOPLink.CallBackHTTPPost()
18:15:17 Object reference not set to an instance of an object.
18:15:17    at VOB_ALGO.Engine.VIOPLink.CallBackHTTPPost(Boolean status, String command, String result) in C:\MyProjects\Home\VOB ALGO\VOB ALGO\VOB ALGO\Engine\VIOPLink.cs:line 124
18:15:17 VIOPLink.CallBackHTTPPost()
18:15:17 Object reference not set to an instance of an object.
18:15:17    at VOB_ALGO.Engine.VIOPLink.CallBackHTTPPost(Boolean status, String command, String result) in C:\MyProjects\Home\VOB ALGO\VOB ALGO\VOB ALGO\Engine\VIOPLink.cs:line 110

**Comment by boratuncer** [comment]
Problem çözüldü.
