### ISSUE TITLE
AVIHL algoritmasında window boyutundan önce sinyal kapatma problemi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#118]
Ekran görüntülerinde gözüktüğü üzere VIHL algoritması 299. satırdan önce çalışması neticesinde sıfırlardan dolayı pozisyon kapatıp tekrar açmaya başlıyor. 

![20170104_bug](https://cloud.githubusercontent.com/assets/23281592/25597144/6ffde4d2-2ecd-11e7-9b72-d197abb38017.jpg)
![20170105_bug](https://cloud.githubusercontent.com/assets/23281592/25597145/7018c4aa-2ecd-11e7-930c-356afc87e627.jpg)
![20170110_bug](https://cloud.githubusercontent.com/assets/23281592/25597147/702d2b34-2ecd-11e7-8f88-30bb37ceae44.jpg)
![20170127_bug](https://cloud.githubusercontent.com/assets/23281592/25597146/702ae112-2ecd-11e7-8551-bc007ab1025a.jpg)

**Comment by boratuncer** [comment]
Problem çözüldü.
