### ISSUE TITLE
AVIHL algoritmasında pozisyon AL ile kapanmışsa yeniden pozisyon açılsın

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#119]
Testlerde gördüğüm kadarıyla max+stdev ve min-stdev çizgilerinden kesişme öncesinde bazen ALAL pozisyonları olabiliyor. Bu yüzden SADECE böyle günlerde ters pozisyon açmamız gerekecek ve aynı şartlarda pozisyon kapatılması gerekiyor. 

Örnek olarak 6 Ocak'ta ALAL'dan sonra ikinci pozisyon tekrar 93.975'den Long pozisyonu açılması ve 94.200'den kapatılması gerekir.

![20170106_bug](https://cloud.githubusercontent.com/assets/23281592/25597234/ebaa508e-2ecd-11e7-8d7a-984b565d7020.jpg)

**Comment by boratuncer** [comment]
Problem çözüldü
