### ISSUE TITLE
AVIHL algoritmasında pozisyon kapandıktan sonra terse pozisyon açamama problemi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#120]
11-17-19 Ocak tarihlerinde pozisyonlar TP veya SL ile kapatıldıktan sonra VIHL'yi tekrar başlatmak gerekiyor. Ekran görüntülerinde nerede VIHL çalıştığını gösterebilmek işaretledim. Anladığım kadarıyla birinci ve ikinci pozisyonlar aynı yönde hareket ederse VIHL çalışıyor ama biri long diğeri short olarak ters yönde hareket ettiğinde çalışmadığını anlıyorum.  

![20170111_bug](https://cloud.githubusercontent.com/assets/23281592/25597381/ae328c7a-2ece-11e7-9d04-0c033deff3f4.jpg)

![20170117_bug](https://cloud.githubusercontent.com/assets/23281592/25597383/ae350c66-2ece-11e7-83b4-9046691f0348.jpg)

![20170119_bug](https://cloud.githubusercontent.com/assets/23281592/25597382/ae32fb74-2ece-11e7-83f7-6c20bbbf93de.jpg)

**Comment by boratuncer** [comment]
Problem çözüldü.
