### ISSUE TITLE
AVIHL Algoritmasında T. Hacim Kuralı Toplu Testi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#124]
POZİSYON AÇILDIKTAN SONRA FİYAT 500 PUAN VEYA DAHA FAZLA KARI GÖRMÜŞ VE T. HACİM YARI YARIYA AZALMIŞ İSE TEKRAR POZİSYON AÇ.

EĞER POZİSYON AÇIK İSE KAPAT TERSİNE POZİSYON AÇ.

**Comment by boratuncer** [comment]
Pozisyon kapalıyken bu koşullara gelirse ne yapalım ?

**Comment by boratuncer** [comment]
Yanlışlılka "Comment" ekleyeceğime "Close" yaptım, pardon

**Comment by erkannurel** [comment]
Pozisyon kapalıyken bir şey yapmayalım

**Comment by erkannurel** [comment]
Yeni şartlara göre bunu yapmaya gerek kalmadı...
