### ISSUE TITLE
Copy paste ederken çıkan hata

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#156]
Program çalışırken anlık olarak bazı analizlerimi yapabilmek için veri listesindeki datanı hepsini seçip excele almak isterken aşağıdaki hata oluşuyor. 

![image](https://cloud.githubusercontent.com/assets/23281592/26202876/aac7fa8c-3be1-11e7-838b-35e71f4ed590.png)

**Comment by boratuncer** [comment]
Adımları tam olarak rica edebilir miyim ?

**Comment by erkannurel** [comment]
Veri listesine tıklayıp CTRL+A ve CTRL + C yapıyorum. Sonra excele gelip CTRL+V ile yapıştırıyorum. Bunu günde 20 sefer yaptığımda oluyor.

**Comment by boratuncer** [comment]
Problemi yeniden yaratamıyorum, işlem sırasında başka birşeyler oluyor muydu ?

**Comment by erkannurel** [comment]
Belki sadece canlı data gelirken bu problem oluyordur. Bir daha böyle bir hata ile karşılaşırsam seni pcye bağlanman için haber vereceğim.

**Comment by boratuncer** [comment]
Veri bağlantısı kurulduğunda datagrid üzerinden kopyalama işlemi kapatıldı, veri bağlantısı sonlandırıldığında tekrar açılacak şekilde değiştirildi.
