### ISSUE TITLE
AVIHL Algoritmasının Tekrar Gözden Geçirilmesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#171]
Hocam AViHL yi tekrar gozden geciriyordum da bir sey farkettim. Örnegin 14.07.2015 tarihinde AVIHL testi yaptigimizda 1200 puan zarar ediyor neden pozisyon cp ile kapaniyor kontrol edebilir misin?

![whatsapp image 2017-07-27 at 13 50 29](https://user-images.githubusercontent.com/23281592/28667348-ccb29c50-72d3-11e7-92c4-16ec115456ce.jpeg)

**Comment by erkannurel** [comment]
13/07/2015 ve 15/07/2015 tarihlerinde ekran görüntülerinde nerede sinyal verilmesi gerektiğini işaretledim. Ekran görüntülerini aşağıda bulabilirsin.

![150713_print screen](https://user-images.githubusercontent.com/23281592/29216391-346ef62e-7eb7-11e7-94b1-19bcf35a70ec.jpg)

![150715_print screen](https://user-images.githubusercontent.com/23281592/29216399-3c249f9a-7eb7-11e7-92ae-00d8acdbe5a1.jpg)

**Comment by boratuncer** [comment]
İlgili değişiklik yapıldı, V0.5.8de eklendi.
