### ISSUE TITLE
AVIHL Adetli Toplu Testi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#173]
Toplu testler sekmesi altına "AVIHL Kümülatif Adetli" ve "AVIHL Kümülatif Adetli Gömülü" testlerinin eklenmesini rica ediyorum.

**Comment by boratuncer** [comment]
Bunu daha önce denemiştim, ciddi zarar ettiriyor, istersen yapayım yine de ?

**Comment by erkannurel** [comment]
Benim bunu isteme sebebim bazı testler yapıyorum bana kolaylık olsun diye. Örneğin ilk pozisyonu AVIHL ile kapattırıyorum. İkinci pozisyona farklı bir algoritma ile devam edebiliyorum. Zarar ettiğimiz günlerde böyle testler yapabilmek için istemiştim. Uğraştırırsa sorun yok yapmayabiliriz.

**Comment by erkannurel** [comment]
Yeni şartlara göre bunu yapmaya gerek kalmadı...
