### ISSUE TITLE
AVIHL kontrol lütfen

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#175]
Hocam AViHL yi tekrar gozden geciriyordum da bir sey farkettim. Örnegin 14.07.2015 tarihinde AVIHL testi yaptigimizda 1200 puan zarar ediyor neden pozisyon cp ile kapaniyor kontrol edebilir misin?

![whatsapp image 2017-07-27 at 13 50 29](https://user-images.githubusercontent.com/23281592/28667348-ccb29c50-72d3-11e7-92c4-16ec115456ce.jpeg)

**Comment by boratuncer** [comment]
sinyal 103.4'ten vermişiz, 3922 nolu tickte 103.425'ten AVIHL yukarı yönlü sinyaller için kapanış koşulu çalışmış ve 0.025 puan TP ile pozisyonu kapatma emri vermişiz.

Algoritmanın en sonunda pozisyonu kapatma fiyatımız 0.1 puan'dan az olursa pozisyonu kapatmayı engelleyen algoritmamız çalışmış ve kapatma emrini iptal etmiş.

**Comment by boratuncer** [comment]
Bu 0.1 puan korumasını koyduğumuzda sonuçlar;

Toplam | 55,26 | 1954
Kar | 6,41 |  

0.1 puan korumasını kaldırdığımızda sonuçlar;

Toplam | 55,95 | 2040 |  
Kar | 4,95 | 

En az 50 işlem daha az yapıyoruz.

**Comment by boratuncer** [comment]
0.1 puan koruması ile devam ediyoruz. İleride gerekirse bunu kaldırırız.
