### ISSUE TITLE
AVIHL Algoritmasında Bir Test

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#177]
AVIHL algoritmasında bir test yapılmasını rica ediyorum. TP: 0.125, 0.225, 0.325, 0.425, .......... , 0.925 SL: Adaptive. AVIHL'yi burada sadece bir kez çalıştıralım. Yani sinyal geldi belirlediğimiz TP'de kar aldı kapandı bir daha algoritmayı çalıştırmayalım. Daha önceki bulduğumuz sonuçlardan daha düşük çıkacak önemli değil. 

Test yapıldıktan sonra günlük olarak sonuçları gönderirsen sevinirim.

**Comment by boratuncer** [comment]
Şuan TP ve SL de adaptif olarak kapanıyor, TP'yi adaptiften çıkarmak biraz zaman alacaktır

**Comment by erkannurel** [comment]
Yeni şartlara göre bunu yapmaya gerek kalmadı...
