### ISSUE TITLE
AVIHL Toplu Test 2

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#178]
Öncelikle AVIHL algoritmamızdaki standart sapmayı 2 ile çarpıp tekrar bir toplu test yapabilir miyiz?

Max + stddev x (+)2
Min - stddev x  (-)2 şeklinde yapıp tüm koşullar aynı olarak tekrar bir toplu test yapıp günlük olarak sonuçları paylaşır mısın?

**Comment by boratuncer** [comment]
V0.5.9 'ta AVIHL algoritması girilirken hem window size (V0.5.8'te sabit 300dü) hemde standart sapma çarpanı parametrik olarak değiştirilebiliyor
