### ISSUE TITLE
Toplu Test Yaparken Bug

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#186]
Toplu test yaparken ister VIHL ister AVIHL'yi seçip günleri eklediğinde test sonlandırılıyor ve ek'teki hatayı alıyorum. 

![bug](https://user-images.githubusercontent.com/23281592/31409617-356c0098-ae15-11e7-8e5a-aca73bf9efaf.jpg)

**Comment by boratuncer** [comment]
DNC'de ilgili kontrat aşağıdaki tarih olarak kayıtlı, dnc.xml dosyası bozulmuş veya eski sürümden kopyalanmış, veya aşağıdaki satırlar eksik olabilir mi ?

      <sdate>01/09/17</sdate>
      <edate>31/10/17</edate>
      <contract>F_XU0301017</contract>

**Comment by erkannurel** [comment]
Yeni versiyonda böyle bir hata ile karşılaşmadım.

**Comment by erkannurel** [comment]
Aldığın hata dosyası aşağıdadır.

[VOBALGO_Error_171013.log](https://github.com/boratuncer/vobalgo/files/1383979/VOBALGO_Error_171013.log)

**Comment by boratuncer** [comment]
dns.xml dosyasını da rica edebilir miyim ?

**Comment by erkannurel** [comment]
Dosya formatını kabul etmediğinden aşağıya satırları kopyaladım.

<?xml version="1.0" encoding="UTF-8"?>

-<DNCItems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">


-<list>


-<DNCItem>

<sdate>02/01/13</sdate>

<edate>28/02/13</edate>

<contract>F_XU0300213S0</contract>

</DNCItem>


-<DNCItem>

<sdate>03/03/13</sdate>

<edate>30/04/13</edate>

<contract>F_XU0300413S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/05/13</sdate>

<edate>30/06/13</edate>

<contract>F_XU0300613S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/07/13</sdate>

<edate>29/08/13</edate>

<contract>F_XU0300813S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/09/13</sdate>

<edate>31/10/13</edate>

<contract>F_XU0301013S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/11/13</sdate>

<edate>31/12/13</edate>

<contract>F_XU0301213S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/01/14</sdate>

<edate>28/02/14</edate>

<contract>F_XU0300214S0</contract>

</DNCItem>


-<DNCItem>

<sdate>03/03/14</sdate>

<edate>30/04/14</edate>

<contract>F_XU0300414S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/05/14</sdate>

<edate>30/06/14</edate>

<contract>F_XU0300614S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/07/14</sdate>

<edate>29/08/14</edate>

<contract>F_XU0300814S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/09/14</sdate>

<edate>31/10/14</edate>

<contract>F_XU0301014S0</contract>

</DNCItem>


-<DNCItem>

<sdate>03/11/14</sdate>

<edate>31/12/14</edate>

<contract>F_XU0301214S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/01/15</sdate>

<edate>27/02/15</edate>

<contract>F_XU0300215S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/03/15</sdate>

<edate>30/04/15</edate>

<contract>F_XU0300415S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/05/15</sdate>

<edate>30/06/15</edate>

<contract>F_XU0300615S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/07/15</sdate>

<edate>31/08/15</edate>

<contract>F_XU0300815S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/09/15</sdate>

<edate>30/10/15</edate>

<contract>F_XU0301015S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/11/15</sdate>

<edate>31/12/15</edate>

<contract>F_XU0301215S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/01/16</sdate>

<edate>29/02/16</edate>

<contract>F_XU0300216S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/03/16</sdate>

<edate>29/04/16</edate>

<contract>F_XU0300416S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/05/16</sdate>

<edate>30/06/16</edate>

<contract>F_XU0300616S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/07/16</sdate>

<edate>31/08/16</edate>

<contract>F_XU0300816S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/09/16</sdate>

<edate>31/10/16</edate>

<contract>F_XU0301016S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/11/16</sdate>

<edate>31/12/16</edate>

<contract>F_XU0301216S0</contract>

</DNCItem>


-<DNCItem>

<sdate>02/01/17</sdate>

<edate>28/02/17</edate>

<contract>F_XU0300217S0</contract>

</DNCItem>


-<DNCItem>

<sdate>01/03/17</sdate>

<edate>05/03/17</edate>

<contract>F_XU0300417S0</contract>

</DNCItem>


-<DNCItem>

<sdate>06/03/17</sdate>

<edate>29/04/17</edate>

<contract>F_XU0300417</contract>

</DNCItem>


-<DNCItem>

<sdate>01/05/17</sdate>

<edate>30/06/17</edate>

<contract>F_XU0300617</contract>

</DNCItem>


-<DNCItem>

<sdate>01/07/17</sdate>

<edate>31/08/17</edate>

<contract>F_XU0300817</contract>

</DNCItem>


-<DNCItem>

<sdate>01/09/17</sdate>

<edate>31/10/17</edate>

<contract>F_XU0301017</contract>

</DNCItem>


-<DNCItem>

<sdate>01/11/17</sdate>

<edate>31/12/17</edate>

<contract>F_XU0301217</contract>

</DNCItem>

</list>

</DNCItems>

**Comment by boratuncer** [comment]
PC^nin tarih formatı değiştirilmesi gerekiyor.
