### ISSUE TITLE
Fiyat Bandın Dışına Çıktığında T. Hacim Kuralı (Short İçin)

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#193]
a) İlk pozisyon senin koyduğun kurala göre kapattık ve bir TP aldık. 
b) Bu TP'yi aldıktan sonra T. hacim -4000 veya daha düşük olduktan sonra t. hacim kuralımızı çalıştırıyoruz ve yarısına geldiğinde Long pozisyonunu O ZAMAN açıyoruz. 
c) Ayrıca, 16:45'ten sonra bir pozisyon açmıyoruz ve tekrar algoritmayı çalıştırmıyoruz (sadece ilk pozisyonda gerçekleşen kuralda).

**Comment by boratuncer** [comment]
b) ve c) şıkları için detay bilgi var mı ?

Örneğin b) şıkkında T.Hacim zaten -10.000'lerde, o zaman hemen t.hacim çalışması mı isteniyor ?

c) şıkkında zaten 16:45'ten sonra pozisyon açmazsak tekrar algoritmayı neden çalıştırıyoruz ?

**Comment by erkannurel** [comment]
B şıkkı için 26/08/2016 tarihinden aşağıda iki görsel ile örnek verdim. 

C şıkkı için ise ilk pozisyonda fiyat bantın dışına çıkıp biz pozisyonumuzu kapattığımızda sadece t. hacim kuralı çalışsın onun dışında tekrar algoritmayı çalıştırmayalım. Öbür türlü sürekli aşağı pozisyon açabilir. Bunun önüne geçmek için. 

![1](https://user-images.githubusercontent.com/23281592/31725599-694054be-b42d-11e7-9e81-66f80ca53f49.png)

![2](https://user-images.githubusercontent.com/23281592/31725608-6f979048-b42d-11e7-96ba-8f2cb8c0e38b.png)

**Comment by erkannurel** [comment]
26.08.2016 tarihinde V.0.5.9b'de log inceleme yaptığımızda; 
1) 236. satırda (Saat - 09:31:39) Sat sinyali alıyoruz   94.075 puandan.
2) 2741. satırda (Saat - 13:38:17) fiyat bandın dışına çıkınca kapat kuralına göre Al sinyali alıyoruz ve 93.950'den pozisyonumuzu kapatıyoruz. **T. hacim şuanda -6,452.** Terse pozisyon açmıyoruz. AVIHL algoritmasını çalıştırmıyoruz. 
3) 3144. satırda (saat - 14:05:40) TP aldıktan sonraki en düşük t. hacimi görüyor. T. hacim: -9,836. Bu saatten sonra T. hacim artmaya başlıyor...
4) Zaman geçiyor ve t. hacim artmaya devam ediyor... 4469. satırda (Saat - 15:35:06) t. hacim en düşük seviyesinden yarısına gelmiş bulunuyor yani -4918'den büyük olan -4911'i görüyor. İşte burada Long sinyali verelim. Fiyat: 93.900'den.
5) AVIHL algoritması standart kapatması gerektiği yerde kapatsın veya CP ile kapansın.

**Comment by erkannurel** [comment]
-4000 ve daha düşükse bu kuralı uygula durumunu eklememişsin. Eklemeni rica ediyorum. Yalnız -4000 yerine -5000 yapalım. Gözümden bişey kaçmış onu düzeltmiş olayım.

**Comment by boratuncer** [comment]
V0.5.9b2'de ekli durumdadır. Telefonda konuştuğumuz üzere fiyat bandın dışına çıkınca T. hacim'i izlemeye başlıyorum, bunun yarısına kadar indiğinde Long sinyali veriyorum.

26.08.2016 tarihi özetinde 4469 nolu satıda V0.5.9b2 Long sinyali veriyor.

**Comment by boratuncer** [comment]
Algoritma son olarak aşağıdaki gibi şekillendi;

1) Fiyat bandın short yönlü dışına çıkınca long sinyali ile TP alarak kapatıyoruz.
2) Bu noktadan itibaren T.Hacim'i izlemeye başlıyoruz ve en düşük noktasını kayıt ediyoruz.
3) Piyasa tersine döndüğünde kayıt edilmiş T.Hacim'in en düşük noktasından 200 puan daha yükselirse ve kapanan pozisyondan 1000 hacim'den az her hangibir yöne hareket etmiş ise terse pozisyon açıyoruz.
4) Terse pozisyon açarsak bu pozisyonun AL ile kapanmasına izin vermiyoruz
5) FB'nin dışına çıkınca (yani 1. madde gerçekleşince) tekrar AL ile pozisyon açmasına izin vermiyoruz.

**Comment by boratuncer** [comment]
V0.5.9c sürümüne eklendi.
