### ISSUE TITLE
AVIHL'de KOFD kaldırılsın mı ?

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#197]

**Comment by erkannurel** [comment]
Nedir KOFD hatırlayamadım...

**Comment by boratuncer** [comment]
Sıcaklık haritası bulmaya çalıştığımız zamanlardan kalma kodlar. Hatırlanmıyorsa kaldırayım ?

**Comment by erkannurel** [comment]
Ok.

**Comment by boratuncer** [comment]
AL0008 algoritması olarak koda eklemişiz

**Comment by boratuncer** [comment]
AL0008 algoritmasının çalışan kısımları kaldırıld, tanımlar #if pragma direktifine alındı.
