### ISSUE TITLE
Log ve Toplu Testler Beklenmeyen BirHata Alıyorum

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#198]
18.01.2016 / 01.09.2016 / 29.09.2016 / 03.03.2017 tarihlerinde aşağıdaki hatayı alıyorum. Bir önceki sürümde böyle bir hata almadım. 

![image](https://user-images.githubusercontent.com/23281592/31796605-11ff6594-b533-11e7-9c98-c379545fc105.png)

**Comment by boratuncer** [comment]
Error log'larını da rica edebilir miyim ? Log'larda nerede hata ile karşılaşıldığını yazar.

**Comment by erkannurel** [comment]
Ek'te bulabilirsin.

[VOBALGO_Error_171019.log](https://github.com/boratuncer/vobalgo/files/1401452/VOBALGO_Error_171019.log)
[VOBALGO_Error_171020.log](https://github.com/boratuncer/vobalgo/files/1401453/VOBALGO_Error_171020.log)

**Comment by boratuncer** [comment]
Problem çözüldü
