### ISSUE TITLE
Markow sonuçlarının analizinde daha geniş bir pencereye bakmak gerekir mi?

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#20]

**Comment by boratuncer** [comment]
"Ayarlar -> Algoritma" menüsünün altında "Markov" alt menüsü oluşturuldu. Bu alt menü üzerinde şimdi ve gelecekte ki Markov algoritma ayarları bulunacak.

İlk madde olarak bakılan CandidateNumber değeri kullanıcı tarafından girilebilen bir alan haline getirildi.
