### ISSUE TITLE
Christmas Tatillerinde Pozisyon Açmayalım.

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#200]
24/12/2015 -0,550 ALSL ---- 5660 satır toplamda -----range: 750 puan
25/12/2015 -0,320 2 AL    - -- 1814 satır toplamda ----- range: 350 puan
26/12/2016 – 0,220 2 AL   - -- 1431 satır toplamda ----- range: 300 puan

Yurt dışında Hıristiyanların Noel tatilinden dolayı yukarıdaki tarihlerde hiç pozisyon açmayalım. Hatta 24-25-26 Aralık tarihlerinde. 1055 puan kazanç sağlamakta.

**Comment by boratuncer** [comment]
Bunun anlamı Türkiye piyasalarını yabancı yatırımcılar yönetiyor demektir.

**Comment by erkannurel** [comment]
Sadece Türkiye değil tüm dünya piyasalarını yönetiyor. 

Diğer tatil günlerine baktım özellikle A.B.D ve Almanya'nın en çok dikkatimi çeken bu ortak tatiller oldu.

**Comment by erkannurel** [comment]
31 Aralık tarihini de yukarıdaki tarihlere ekleyebiliriz.

**Comment by boratuncer** [comment]
Bunu elle yapsak, programa koymasak ?

**Comment by erkannurel** [comment]
Olur tabiki.
