### ISSUE TITLE
Kaybettiğimiz puanların ortalaması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#202]
Yaptığımız 520 günlük testde kaybettiğimiz pozisyonları (gün bazında değil) görebilir miyim? Kayıpların ortalamasını öğrenebilir miyim?

Bunu öğrenmek istememin sebebi gerçek trade'de başlandığında maddi dengemizi bozacak durumların oluşup oluşmadığını anlayabilmek içindir.

**Comment by boratuncer** [comment]
Ben bunu anlamadım, nasıl bir inceleme gerekiyor

**Comment by erkannurel** [comment]
520 günlük testimizde tüm zarar eden pozisyonlarımıza bakalım (Zarar eden günlere değil). Bu zarar eden pozisyonlarımıza baktığımızdan bize en çok kaybettiren pozisyonlarımız hangileridir ve kaç puandır? Bu günleri öğrenebilir miyim?

İkinci olarak tekrar bu zarar eden pozisyonlarımıza bakalım ve sadece zarar eden pozisyonlarımızın ortalamasını hesaplayalım bakalım ortalama ne kayıp ediyoruz pozisyon başı?

**Comment by boratuncer** [comment]
"Başarı yüzdemiz ile ilgili bir test #231" nolu bug için verilen çözüm bu bug içinde yeterli mi ?

**Comment by erkannurel** [comment]
Yeterli.
