### ISSUE TITLE
ALSL Aldığımız Günlerdeki Algoritma

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#205]
Detaylar girilecek...

**Comment by boratuncer** [comment]
1) AL aldığımız günlerde kaç puan ile zarar etmişsek, terse pozisyon açtığımızda zarar kadar TP aldığımızda pozisyonu kapatıyoruz.
2) Terse pozisyon açmak içinde sadece 0.8 puan'dan küçük zarar etmişsek bu işlemi yapıyoruz
2) İkinci pozisyon kapatıldığında 200 tick boyunca her hangibir algoritmanın çalışmasını engelle
