### ISSUE TITLE
ALAL'den sonra açılan pozisyonlar

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#206]
1) ALAL'den sonra toplam zarar xxx kadar olursa pozisyon açma....

2) Açılan pozisyon y kadar zarar görmüş ise AL ile kapatma...

**Comment by erkannurel** [comment]
2. madde de y kadar zarar görmüş tüm pozisyonlarda bu kural uygulanıyor. Kontrol edelim lütfen.

**Comment by boratuncer** [comment]
İlk kural V0.5.9f olarak eklendi. İkinci kural getiri olmadığı için eklenmedi.
