### ISSUE TITLE
Grafikte Değerler Doğru Göstermiyor

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#212]
Grafikte değerler doğru göstermiyor. Sanırım sadece maxofminstddev ve minofmaxstddev değerleri yazıyor. Bir de kutucuk çok sağda kusuratlar görünmüyor. Ekran görüntüsü aşağıdadır.

![hata 1](https://user-images.githubusercontent.com/23281592/32102460-18f9fea2-bb25-11e7-98c3-8cae63bf89c4.png)

**Comment by boratuncer** [comment]
Problem çözüldü.
