### ISSUE TITLE
Grafikte kutucukta problem

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#213]
Grafiği aşağı alıp sonra tam ekran yaptığımızda kutucuk küçülüyor ve değerler okunmuyor. Ekran görüntüsü aşağıdadır. 

![hata 2](https://user-images.githubusercontent.com/23281592/32102516-5df2c6e2-bb25-11e7-875b-0fba7181c9ca.png)

**Comment by boratuncer** [comment]
Problem çözüldü.
