### ISSUE TITLE
Başarı yüzdemiz ile ilgili bir test

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#231]
İlk açtığımız pozisyonların yüzde kaçında başarı oluyoruz yüzde kaçında başarısız oluyoruz? Bunu merak ediyorum. Aynı şekilde ikinci ve üçüncü açtığımız pozisyonlarda durum nedir?

**Comment by boratuncer** [comment]
Excell'de bunun için COUNTIF ile basit bir formül yazdım, biraz el oyalıyor ama rahat yapılabiliyor

![image](https://user-images.githubusercontent.com/19672389/32547865-f0a6100c-c494-11e7-8854-ceb1c6e1c1d0.png)
