### ISSUE TITLE
Emir Göndermede Alınan Hata

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#233]
Kontrat otomatik kısmından dolayı kaynaklanabilecek emir gönderme hatası aldık. 

Aracı kurum : Parametre hatası!REF:0
--
Aracı kurum : Parametre hatası!REF:0

**Comment by boratuncer** [comment]
Kontrat isimleri düzenlendi, problem çözüldü

**Comment by boratuncer** [comment]
Problem V0.6.1'de halen devam ediyor

**Comment by boratuncer** [comment]
Problem aracı kurumdan alınan yeni bilgilerle düzeltildi.
