### ISSUE TITLE
Aracı kuruma bağlanma problemi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#25]
Mail gönderildi.

06:50:09 The remote server returned an error: (404) Not Found.
06:50:09    at System.Net.HttpWebRequest.GetResponse()
   at VOB_ALGO.Engine.HTTPPost.postThread(Object args)
06:50:09 HTTPPost.postThread()

**Comment by boratuncer** [comment]
HTTPPost class'ında exception handle ederken this.OnPost(false, command, "Error"); ile alınan hatayı bir üst katmana bu kod ile gönderiyoruz. "command" değişkeni exception yediğimizde GC tarafından silinmiş oluyor.

Yeni versiyonda çözüldü
