### ISSUE TITLE
ALAL Pozisyonlar da İsimlendirme Hatası

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#258]
ALAL pozisyonlarımızda ikinci pozisyonlarında 500 puan terse gittiği için SL yemişiz ama yazan AL.

**Comment by boratuncer** [comment]
örnek gün var mı ?

**Comment by erkannurel** [comment]
Tamamı

31.07.2015 | -1,040 | 4 | ALAL
3.08.2015 | -0,915 | 4 | ALAL
2.10.2015 | -0,890 | 4 | ALAL
2.02.2016 | -0,990 | 4 | ALAL
4.03.2016 | -1,165 | 4 | ALAL
21.03.2016 | -1,065 | 4 | ALAL
14.04.2016 | -1,015 | 4 | ALAL
20.04.2016 | -1,015 | 4 | ALAL
27.05.2016 | -1,015 | 4 | ALAL
10.06.2016 | -1,040 | 4 | ALAL
20.07.2016 | -1,640 | 4 | ALAL
10.08.2016 | -1,015 | 4 | ALAL
22.08.2016 | -1,015 | 4 | ALAL
6.09.2016 | -0,965 | 4 | ALAL
30.11.2016 | -1,065 | 4 | ALAL
7.12.2016 | -0,940 | 4 | ALAL
9.12.2016 | -1,090 | 4 | ALAL
16.12.2016 | -0,815 | 4 | ALAL
10.01.2017 | -1,090 | 4 | ALAL
18.01.2017 | -0,915 | 4 | ALAL
9.02.2017 | -1,015 | 4 | ALAL
23.03.2017 | -0,815 | 4 | ALAL
7.07.2017 | -0,890 | 4 | ALAL
14.07.2017 | -0,915 | 4 | ALAL
8.08.2017 | -1,165 | 4 | ALAL
14.09.2017 | -1,040 | 4 | ALAL
15.09.2017 | -1,090 | 4 | ALAL

**Comment by boratuncer** [comment]
31.07.2015 sinyalleri
----------------------------------------
Sat Sinyali : 15:28:49 - 102,550 - TP
Al Sinyali : 09:39:06 - 101,650 - AL
Al Sinyali : 09:38:21 - 101,550 - TP
Sat Sinyali : 09:28:46 - 101,800 - AL

03.08.2015'de 2. pozisyon gerçekten AL ile kapanıyor.

02.10.2015'de 2. pozisyon gerçekten AL ile kapanıyor.

**Comment by boratuncer** [comment]
0.1 bandı algoritmasına takılan günler için pozisyonu kapatma sebebi AL yerine SL olarak değiştirildi.
