### ISSUE TITLE
Otomatik Log Gönderme Seçeneği

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#26]
Program gün sonu kapanıştan sonra otomatik olarak log'u mail göndersin. Bu işlemi bir buçuk yıldır manuel olarak yapmaya çalışıyoruz.

**Comment by boratuncer** [comment]
Programın piyasanın kapanış saatinden sonra bile açık olması gerekiyor. Bu sıkıntı yaratmaz mı ?

**Comment by boratuncer** [comment]
Yanlışlıkla Comment tuşu yerine Close tuşuna bastım

**Comment by erkannurel** [comment]
Program zaten her gün piyasa kapandıktan sonra da açık kalıyor. Bazen 10 dakika bazen 3-4 saat açık bıraktığım oluyor. Nasıl bir sıkıntı yaratabilir anlayamadım?

**Comment by boratuncer** [comment]
Özellik eklendi.
