### ISSUE TITLE
TPAL(SL) pozisyonlarından sonra açılan pozisyonlar

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#264]
V.0.6.2 ile V.0.6.2a versiyonları arasında 1,105 puanlık bir fark oluşmakta. Bunun sebebi TPAL(SL) pozisyonlarından sonra açılan veya açılmayan pozisyonlardan dolayıdır. 

V.0.6.2 versiyonunda TPAL pozisyonlarından sonra tekrar zarardan dolayı terse açılmış ama V.0.6.2a versiyonunda TPAL pozisyonlarında sonra algoritma tekrar başlatılmış bu yüzden bu fark oluşmaktadır. Bu konuda ne yapabiliriz? 

Karşılaştırmalı sinyaller word belgesinde gösterilmektedir.

[TPAL(SL) Poz..docx](https://github.com/boratuncer/vobalgo/files/1468336/TPAL.SL.Poz.docx)

**Comment by boratuncer** [comment]
"ALAL Pozisyonlar da İsimlendirme Hatası #258" bug için yapılan değişiklikten dolayı kaynaklanıyor.

Pozisyonu AL ile değil, SL ile kapattığımız için bir sonraki tick'te algoritmalar farklı çalışıyor. V0.6.2'de AL ile kapanınca terse pozisyon aç çalışırken, V0.6.2a'da pozisyonlar AL ile kapanmadığı için terse pozisyon çalışmamış.

İki şekilde çözebiliriz;
1. V0.6.2'de olduğu için 100 puan kuralına takılan 500puan'lı SL'lerde kapanış pozisyonu AL olarak isimlendirebiliriz.
2. V0.6.2.a'da olduğu gibi yukarıdaki kurala takılan günlerde yine extradan terse pozisyon açabiliriz.
