### ISSUE TITLE
Başka VIOP senetlerin verileri kayıt edilsin mi ?

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#266]

**Comment by erkannurel** [comment]
Evet lütfen kaydedilsin. Aşağıdaki dosyada kodları bulabilirsin.

[Diğer Vadeliler.xlsx](https://github.com/boratuncer/vobalgo/files/1470585/Diger.Vadeliler.xlsx)

**Comment by erkannurel** [comment]
XAUUSD
EURUSD
BRENT 
24 saat açık piyasalar. Testi yapılacak.

**Comment by boratuncer** [comment]
LOGER uygulaması yazıldı.
