### ISSUE TITLE
Günlük, Haftalık, Aylık Takvim Uygulaması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#27]
Programa girdiğimizde günlük, haftalık, aylık olarak hem Türkiye'de hem de Amerika'da açıklanacak verilerin listesi ve tahminlerini çekebilelim. Örneğin Amerika için http://www.forexfactory.com/ websitesinden yararlanabiliriz. Türkiye ve Diğer seçeceğimiz ülkeler için ise http://tr.investing.com/economic-calendar/ adresinden yararlanabiliriz. 

Burada önemli olan açıklanacak datanın Türkiye saati, ne açıklanacağı, önem derecesi ve tahminin ne olduğudur. Data açıklandıktan sonra da ne sonuçun ne geldiğidir.

**Comment by boratuncer** [comment]
Böyle bir özellik programa eklersek programın amacı dışına çıkmaz mıyız ?

Bunun için ayrı bir program yazsak daha uygun olmaz mı ?

**Comment by boratuncer** [comment]
Yanlışlıkla Comment tuşu yerine Close tuşuna bastım

**Comment by erkannurel** [comment]
Ben kesinlikle programın amacı dışına çıkacağımızı düşünmüyorum. Sebebi ise günlük açıklanacak verilerin beklentisi "Teknik ve Temel Analizin" yardımcı unsurlarıdır. Algoritmik trading teknik analizi içine alır. 

Ayrıca, ileride haber algoritmasıda yazılabilir. Örneğin, ayda bir açıklanan USA işsizlik rakamları beklenin altında veya üstünde geldiğinde şu aksiyonu al gibi.

İkinci söylediğin ayrı bir program yazsak olmaz mı diye sormana cevabım tabiki olabilir.

**Comment by boratuncer** [comment]
Bunu algoritmaya dökebilecek miyiz ? Dökemeyeceksek programa eklemeyelim.

**Comment by boratuncer** [comment]
Yeni programın isimi IReader veya IFetcher olabilir, ne dersin ?

**Comment by erkannurel** [comment]
Ben pek bağlantı kuramadım. 

Calendar / Takvim gibi bir isim koysak daha anlamlı olmaz mı?

**Comment by boratuncer** [comment]
Olur, InfoReader kısaltması olarak IReader düşünmüştüm. Calender yaparım

**Comment by boratuncer** [comment]
Verilerin alınacağı siteler nelerdir ? Hangi verileri indirmemiz gerekiyor ?

**Comment by erkannurel** [comment]
Öncelikle format şu şekilde olmalı: 
Tarih / Datanın Açıklanma Saati (TSİ) / Hangi Ülke / Piyasalara Etkisi / Açıklanacak Data / Ne Tahmin Ediliyor / Önceki Açıklanan data 

Calendarımıza ileriki tarihteki dataları elle de girebilme imkanımız olması daha iyi olur çünkü herşeyi sitelerden çekemeyiz. Örneğin, Cumhurbaşkanının piyasaların için açıklayacağı önemli bir haber olabilir, S&P'nin ülke notu açıklaması olabilir vs. 

![capture](https://user-images.githubusercontent.com/23281592/32778685-e444df62-c94b-11e7-9b3d-26cf7f36c115.JPG)

**Comment by boratuncer** [comment]
Özellik eklendi.

![image](https://user-images.githubusercontent.com/19672389/42017599-551c60b6-7ab8-11e8-9ce1-2adfb494371f.png)

**Comment by boratuncer** [comment]
https://www.investing.com/webmaster-tools/economic-calendar
