### ISSUE TITLE
Osmanlı Yatırım ile entegrasyon süreci başlatılacak

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#276]
Osmanlı Yatırım ile entegrasyon süreci başlatılarak

**Comment by erkannurel** [comment]
Osmanlı Yatırım ile görüşüldü. Matriks programının kahin üzerinden emir gönderebileceğimizi söylediler. Bizim sistemimize uymadığını düşünüyorum ama yine de uyarlayabilir miyiz diye araştıracağım.

**Comment by boratuncer** [comment]
Bu konuda bir dönüş yapmadılar değil mi ?

**Comment by erkannurel** [comment]
Altyapıları bizim sistemimize uymuyor.
