### ISSUE TITLE
Elimizdeki Karı Kaçırmamak için algoritma

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#277]
Şöyle bir algorimta yapılabilir, sinyalden sonra local max. kontrol edilir, 500 puan üzerindeyse TP, lokal max. kayıt edilmeye başlar, 200 puan düştüyse hemen TP ile kapatılır

**Comment by erkannurel** [comment]
Şöyle bir şey rica edilecek: Sadece TP günlerdeki hareketi anlayabilmek için. Bu günlerde açılan ilk pozisyonda maksimum kaç puan o yöne hareket ettiği ve sonrasında kaç puanda kapandığını bilirsek doğru müdahale şansımız artar.

**Comment by erkannurel** [comment]
Örneğin, 20.11.2017 tarihinde 132.325 short dedik 131.350 ye kadar indi 132.175 den tp aldik. Ciddi bir kar kaçırmış olduk.

**Comment by boratuncer** [comment]
Ufak bir çalışma rica edebilir miyim ? Elimizde tek pozisyonda 1000 puan'ın üzerinde kar yapan kaç gün var ? Hangi günler ?

**Comment by erkannurel** [comment]
ilk pozisyonun maksimum kac puan gittigini gorebilirsin sadece TP ile baslayan gunlere baktim. Fiyat Bandi kuralinin calistigi gunleride ozellikle yazdim gerekirse ayirabilmek icin. 

[ZARARLI GÜNLER.xlsx](https://github.com/boratuncer/vobalgo/files/1487128/ZARARLI.GUNLER.xlsx)
