### ISSUE TITLE
Sabit SL uygulaması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#278]
İlk pozisyon 0.100 puan kuralından dolayı 135,350 - 135.400'de kapanmadı (4100. satırda) ve yukarı gitmeye devam etti sonrasında 1.000 puan yukarıda AL pozisyonu ile kapandı. Sinyaller ve Log dosyası aşağıdadır.

Al Sinyali : 12:26:32 - 136,375 - AL
Al Sinyali : 12:25:55 - 136,350 - AL
Sat Sinyali : 10:12:12 - 135,350 - AL

[VOBALGO_Data_171114.log](https://github.com/boratuncer/vobalgo/files/1470324/VOBALGO_Data_171114.log)

**Comment by boratuncer** [comment]
4101 nolu noktada 0 kar ile TP alabilirken 100 puan kuralı yüzünden burayı kaçırmışız. Buna bir implementasyon yapılabilir ve belirli şartlar altında 100 puan kuralı devre dışı bırakılabilir.

Ayrıca 100 puan kuralı şöyle çalışıyor;
1) Pozisyon açıldıktan sonra piyasa pozisyon açılış fiyatına 100 puan veya daha yakınlaşıyor ama pozisyon kapanmıyorsa incelemeye al.
2) Pozisyon kapandıktan sonra 2. pozisyon 500 puan SL'ye düşerse AL ile kapat

Yukarıda ki algoritma yanlış yazılmış, aslında ilk pozisyonu da 500 puan sonrası SL ile kapatması gerekiyor. Bunu düzeltip toplu test yaptığımızda karımız tam 6.000 puan düştü. Yanlışlıkla doğru yapmışız :)

**Comment by boratuncer** [comment]
100 puan kuralını sadece 1. pozisyonlar için uygularsak 14.000'den fazla puan kaybediyoruz.

**Comment by erkannurel** [comment]
Kuralı yanlış uygulandığını görüyorum. Pozisyon açıldıktan sonra 0.500 puan terse pozisyon hareket etmiş ise kapat olarak girmişsin. Bizim istediğimiz 0.100 kuralı uygulandıktan sonra eğer tekrar zarar yazıyorsa ve bu zarar da 0.500 bulmuş ise pozisyonu kapat.

**Comment by boratuncer** [comment]
Kural öyle çalışıyor zaten 0.100 kuralı uygulandıktan sonra izlemeye başlıyoruz. Zarar 500 puana gelince kapatıyoruz.

Ama yanlışlıkla 1. pozisyon zararı 500 puana gelince değil 2. pozisyonun zararı 500 puana gelince kapatıyoruz.

**Comment by boratuncer** [comment]
Bug'ı kapatalım mı ?
