### ISSUE TITLE
Zararlı Pozisyonları Açılmadan Engelleyecek Bir Mekanizma

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#280]

**Comment by erkannurel** [comment]
Ağırlıklı ortalamaya göre fiyat karşılaştıralabilir. 

Pozisyon açıldıktan sonra da karşılaştırma yapılmaya devam edilebilir.

**Comment by boratuncer** [comment]
Bu konuda bir gelişme var mı ? Yoksa Won't Fix diyerek kapatalım mı ?

**Comment by erkannurel** [comment]
Çözülemedi.
