### ISSUE TITLE
ALAL'lardan sonra pozisyon açılması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#281]
Gün içinde özellikle de piyasada erken saatte ALAL aldığımızda 0.800 kuralından dolayı tekrar pozisyon açılmıyor. Günün kalan kısmında yapılan tüm hareketler kaçırılıyor. Bu yüzden tekrar pozison açabilmek için ek bir algoritma türetilmelidir.

**Comment by boratuncer** [comment]
Daha zarar ettirdiği görüldü.
