### ISSUE TITLE
Erken TP almak için bir algoritma

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#282]
1. Pozisyon açıldıktan sonra TP yönüne 700 puan veya daha yukarı hareket ederse 700 puandan sonra local max. kayıt altına almaya başla
2. Piyasa local maximumdan 200 puan daha aşağıya düşerse pozisyonu TP ile kapat
3. Kapandığı yerde terse pozisyon aç
4. Terse açılmış pozisyon ile piyasa fiyatı 300 puandan az ise AL ile kapanmasına izin verme

**Comment by erkannurel** [comment]
Yazdıklarını incelediğim kadarıyla özellikle 1. ve 2. maddenin bize büyük kayıp sağlayacağını düşünüyorum. 

TPTP, TPCP ve TP günleri incelediğimde bize toplamda 110k gelir sağlamış ve kural uygulanırsa bunları kaybedeceğimizi ve hatta o günlerde zarar yazacağımızı düşünüyorum (4 maddeyi de uyguladığımızda). Bu yüzden bana mantıklı gelmiyor. 

Denemek istersen kararı sana bırakıyorum.

**Comment by boratuncer** [comment]
Toplam karımızı düşürdü.

Toplam | 80,055 | 2262 |  
Kar | 23,505 |   |
