### ISSUE TITLE
Error Logları

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#283]
14.11.2017 ve 15.11.2017 de error dosyalarında bazı hataları yazılı lütfen kontrol edebilir misin?

[VOBALGO_Error_171114.log](https://github.com/boratuncer/vobalgo/files/1473966/VOBALGO_Error_171114.log)
[VOBALGO_Error_171115.log](https://github.com/boratuncer/vobalgo/files/1473967/VOBALGO_Error_171115.log)

**Comment by boratuncer** [comment]
14.11.2017'de 11:38:21 ve 12:36:28 saatlerinde, 15.11.2017'de 10:34:06 saatinde PC işlem hızına bağlı olarak log kaçırılmış.
