### ISSUE TITLE
Emir Gönderme Kapalı 

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#284]
Sabah programı açtığımda emir gönderme ikonu kapalı idi. Oysaki dün akşam emir göndermeyi açık bırakıp, programı kapattım. Lütfen kontrol edebilir misin?

**Comment by boratuncer** [comment]
Problemi yaratamadım, tekrarlayabildin mi ?

**Comment by erkannurel** [comment]
Hayir.
