### ISSUE TITLE
User Sinyalde Bug ve Çift Tıklama Çalışmıyor

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#286]
User Sinyal gönderdiğimiz de resim de işaretlediğim sinyalde saat yanlış gösteriyor. Ayrıca user sinyallere çift tıkladığımda veri listesinde ilgili satırı görmüyorum ve her hangi bir renk olarak gözükmüyor. 

![bug](https://user-images.githubusercontent.com/23281592/32834372-6bfad804-ca13-11e7-9e62-cbabbb8f6d60.jpg)

**Comment by boratuncer** [comment]
User sinyali işlem saatini ve işlem yaptığı fiyatı işlem yapılan tick'in saati ve fiyatı sisteme veriyor. Eğer saat yanlış ise fiyatında yanlış olması gerekir.

**Comment by erkannurel** [comment]
Son iki gönderdiğim sinyalinde de saati aynı ama ben en az aralarında iki dakika fark ile gönderdim. Aynı dakikada aynı saniyede iki emir göndermedim. Muhtemelen son sinyal bir önceki sinyalin saatini alıyor. Gönderdiğim ekran görüntüsünde son iki sinyale bakarsan (birini işaretlemişim) kanıtını görebilirsin.

**Comment by boratuncer** [comment]
Kod şöyle imlemente edildi;

DataItem dt1 = dataList.itemDataList[dataList.itemDataList.Count - 1];

Verileri tuttuğum listede ki en güncel item üzerinden işlem yapıyoruz. Yakaladığım sinyalde değil. Bunun testini yapmak çok kolay, uygulama sinyal göndermeden elle pozisyon açarsak senin dediğin senaryoya göre çalışmaması lazım.

**Comment by boratuncer** [comment]
Çift tıklama tarafı çözüldü. Saat halen yanlış olduğu gözlemleniyorsa ayrı bir ticket rica edeceğim :)
