### ISSUE TITLE
Kontrat Hareketlerinde Tarih Kısmı Kontrol Edilecek

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#291]
Aracı kurumlar üzerinden kontrat hareketlerinde günün tarihi yazılmasına rağmen 1 gün önceki tarih de geliyor.

**Comment by boratuncer** [comment]
Aracı kurum taratından gönderilen bir gün öncesine ait veriler dikkate alınmayacak şekilde değiştirildi.
