### ISSUE TITLE
AL sonrası Maxofms & Minofms kuralı

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#295]
1. İlk pozisyon AL ile kapanacak.
2. Terse pozisyon açılacak.
3. Long için fiyatın Maxofms ile kesişmesine bakılacak (Gerekirse tolerans değeri koyulacak).
4. Short için fiyatın Minofms ile kesişmesine bakılacak (Gerekirse tolerans değeri koyulacak).
5. AL'dan 0.100 ve sabit SL (0.500) kuralları disable edilecek. 
6. Bu durumlar gerçekleştikten sonra ŞİMDİLİK yeni bir pozisyon açılmayacak.

**Comment by boratuncer** [comment]
Bu konuda bir gelişme var mı ? Yoksa Won't Fix diyerek kapatalım mı ?

**Comment by erkannurel** [comment]
Çözülemedi.
