### ISSUE TITLE
ALAL sinyalinden sonra SL 

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#31]
15/11/2016 tarihinde ALAL sinyalinden sonra tekrar SL yememiz gerekirken sinyal gelmedi. Log dosyasını ev pcden alabilirsin buradan gönderemedim.

![untitled](https://cloud.githubusercontent.com/assets/23281592/20340083/84f033f8-abe8-11e6-963c-1d2f30ef35f4.png)

**Comment by boratuncer** [comment]
Settings class'ı DataList class içine aktarılamadığı için statik olarak 18:15 olarak yazıldı. Ayarlar penceresinden değiştirilemiyor.
