### ISSUE TITLE
Arka Arkaya TPTP Sinyal Vermesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#319]
14/10/2015 tarihinde saat 15:30'da TPTP sinyal vermiştir. Ekran görüntüsü aşağıdadır. İncelenmesini rica ediyorum. 

![capture](https://user-images.githubusercontent.com/23281592/32984864-b6f9caa0-ccbf-11e7-9ee6-93905085406c.JPG)

13/10/2015 - 28/06/2016 tarihlerinde de durum aynı.

**Comment by boratuncer** [comment]
Problem çözüldü.
