### ISSUE TITLE
Sinyal Hatası

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#322]
134,000'den long sinyali verildikten sonra 133,850'e düşüyor ve tp aldığı yazıyor. Kontrol edebilir misin?

![capture 2](https://user-images.githubusercontent.com/23281592/32995976-81ed02c2-cd8d-11e7-8103-b3369f507580.JPG)

**Comment by boratuncer** [comment]
Bu senaryoda fiyat > Maxstddev'in üzerinde olduğunda hep TP de kalacağımızı farzetmiş, fiyat'ın SL'de kalacağını düşünememiştik. Problem çözüldü.
