### ISSUE TITLE
TP/SL algoritmasında ufak güncelleme

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#323]
TP/SL algoritmasında şuan karşılaştırmada ">=" kısımı TP olarak, "<" kısımı SL olarak işaretliyor.

"=" olan durumlar için TP yerine SL veya AL yapsak kazancımız nasıl değişir ?

**Comment by erkannurel** [comment]
Bence pek değişmez çünkü böyle bir gün pek göremedim.

**Comment by boratuncer** [comment]
Sonuçları değiştirmedi
