### ISSUE TITLE
Markov Algoritmasını Oluşturma

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#34]
1) Giriş fiyatı ile hedeflenen fiyat arasındaki absolute fark xxx eşit veya üstünde ise ve giriş fiyatı hedeflenen fiyattan küçük ise LONG pozisyonu aç. 

2) Giriş fiyatı ile hedeflenen fiyat arasındaki absolute fark xxx eşit veya üstünde ise ve giriş fiyatı hedeflenen fiyattan büyük ise SHORT pozisyonu aç. 

3) Pozisyon açıldıktan sonra hedeflenen fiyata geldiği takdirde tp al.

4) Pozisyon açıldıktan sonra hedeflenen fiyata (TP noktasına) gelmeden yeni bir tahmin gelmiş ise ve aynı yönde sinyal gelmiş ise devam et (bir önceki pozisyonu kapatma yani). Eğer gelmemiş ise pozisyonu giriş fiyatı ile kapat. TP'sini en son açılan pozisyona göre revize et (Eğer giriş fiyatı ile hedeflenen fiyat arasındaki fark xxx eşit veya üstünde ise).

5) 18:15'ten sonra pozisyon açık ise cp kuralını çalıştır ve tekrar pozisyon açma.

[Markov Sonuç Değerlendirme.xlsx](https://github.com/boratuncer/vobalgo/files/617335/Markov.Sonuc.Degerlendirme.xlsx)

**Comment by boratuncer** [comment]
İstek V0.5.1de çözüldü.

Madde 4 te pozisyonu kapatıyoruz fakat yeni posizyon açmıyoruz.
