### ISSUE TITLE
Loger Data Gelme Problemi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#341]
Loger'da senetleri giriyorum. Veri bağlantısını kur dediğimde data gelmiyor ve program donuyor.

**Comment by boratuncer** [comment]
Error ve Data log'ları var mı ?

**Comment by erkannurel** [comment]
Donma problemi yok ama data bir sefer geliyor sonrasında bir daha data gelmiyor. Log dosyası ek'te

[LOGER_Data_171128.log](https://github.com/boratuncer/vobalgo/files/1511278/LOGER_Data_171128.log)

[LOGER_Error_171128.log](https://github.com/boratuncer/vobalgo/files/1511279/LOGER_Error_171128.log)

**Comment by erkannurel** [comment]
Yeni Log'lar...

[LOGER_Data_171128.log](https://github.com/boratuncer/vobalgo/files/1511322/LOGER_Data_171128.log)
[LOGS_Error_171128.log](https://github.com/boratuncer/vobalgo/files/1511323/LOGS_Error_171128.log)

**Comment by boratuncer** [comment]
Aktif olarak aşağıdaki parametreler için bilgi istiyorduk.

".SON", ".ADET.MTX", ".TS_ISLEMYONU", ".TS_ZAMAN", ".G.ADET", ".ALIS", ".SATIS", ".ACIK POZ.", ".NET.FARK.ADET"

Bunu sadece 1 parametreye indirdik.

".SON"
