### ISSUE TITLE
Ddeserver da Data Akmıyor

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#342]
Ddeserverda günü seçiyorum başlat diyorum programdan da veri bağlantısını kuruyorum ama data gelmiyor. Kontrol edebilir misin?

**Comment by boratuncer** [comment]
DDEServer uygulaması aslında veriyi gönderiyor ama VobAlgo ilgili senet için veri gelmiyorsa ekranda göstermiyor. Bu testleri yaparken eğer Ayarlar menüsü altında bulunan "Otomatik Kontrat Seçimi" açık ise VobAlgo'nun beklediği senet isimi ile DDEServer'ın gönderdiği senet isimi çok büyük oranda farklıdır.
