### ISSUE TITLE
DDE Serverda Fazla Gelen Data

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#346]
15.09.2017 tarihini hem log inceleme hem de dde server ile grafik çizdirdim. Bunu yaparken yaklaşık 3500 data fazla geldi. Log incelemede satır sayısı 7755 iken Dde serverda satır sayısı 10500 idi. Hem log incelemenin hem de dde server ile yapılan incelemenin ekran görüntülerini aşağıda bulabilirsin. 

**LOG İNCELEME**
![log inceleme](https://user-images.githubusercontent.com/23281592/33229904-a4c8bb6e-d1e9-11e7-9780-67744362e239.JPG)

**DDE SERVER**
![dde server](https://user-images.githubusercontent.com/23281592/33229906-a9adc6a6-d1e9-11e7-992b-aa3726ce0bea.JPG)

**Comment by boratuncer** [comment]
Problemi yeniden yaratamadım. Örnek dosyada log incelemede ve dde server üzerinden de 1814 tane tick geliyor.

Ama dde server ile bağlantı kurulduğunda (kaldığı yerden devam etmesi amacıyla) eski verileri "Veri Listesi" ekranından silmiyoruz. Bu problemi yaşandığında önce Log İnceleme yapılmış sonra ekranı temizlemeden direk DDE Server ile veri iletişimine geçilmiş olabilir.


[VOBALGO_Data_151225.log](https://github.com/boratuncer/vobalgo/files/1571401/VOBALGO_Data_151225.log)

**Comment by boratuncer** [comment]
Bunu inceleme şansın oldu mu ?

**Comment by erkannurel** [comment]
Problem tekrar yaratılamadı.
