### ISSUE TITLE
Log inceleme yaptığımızda oluşturduğu dosya

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#35]
Log inceleme yaptığımızda oluşturduğu log dosyası hem normal log dosyaları ile karıştırılıyor hem de fazla log inceleme yaptığımızda yüksek megabyte'larda dosyalar oluşabiliyor. Eğer programın normal düzenini bozmayacaksa log inceleme yaptığımızda text dosyamızı oluşturmasın.

**Comment by boratuncer** [comment]
"Ayarlar -> Kişisel Ayarlar" bölümüne bir checkbox konuldu. Böylece kullanıcı istediği zaman "Log İnceleme" sırasında log almayı kapatabilecek
