### ISSUE TITLE
İzleyen band TP/SL kuralı

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#360]
**Yukarı Yönlü Piyasa**
LONG pozisyonu için
•	MinStddev (Kırmızı) ile MaxOfMinStdDev (Yeşil) aynı olduğunda izlemeye al
•	MinStdDev < MaxOfMinStdDev’den küçük olduğunda ve TP yönünde XXX puan veya SL yönünde ZZZ puan alındığında pozisyonu kapat
•	MinStddev (Kırmızı) ile MaxOfMinStdDev (Yeşil) arada YYY kadar fark olduğunda izlemeye al
•	MinStdDev = MaxOfMinStdDev olduğunda ve TP yönünde XXX puan alındığında pozisyonu kapat
Terse pozisyon açacak mıyız ?
SHORT pozisyonu için
•	Fiyat (Beyaz) MinOfMaxStdDev’in XXX kadar altına inmiş ise izlemeye al
•	Fiyat MinOfMaxStdDev’i aşağıdan yukarıya kesiyorsa pozisyonu kapat

**Aşağı Yönlü Piyasa**
LONG pozisyonu için
•	Beyaz Yeşil’in altına iner ve fark XXX kadar olursa izleme başla (veya kapat)
•	Beyaz Yeşil’i yukarı yönlü keserse kapat

SHORT pozisyonu için
•	MaxStdDev (Turkuaz) ile MinOfMaxStdDev (Mor) arada fark YYY puan olduğunda izlemeye al
•	MaxStdDev = MinOfMaxStdDev olduğunda ve TP yönüne XXX puan alındığında pozisyonu kapat

**Comment by erkannurel** [comment]
•	MinStddev (Kırmızı) ile MaxOfMinStdDev (Yeşil) aynı olduğunda izlemeye al **_-- _Long pozisyonu olduğunda bu durum her zaman gerçekleşmektedir bu yüzden bu kural ile izlemeye almak anlamsız olur.__**

•	MinStdDev < MaxOfMinStdDev’den küçük olduğunda ve TP yönünde XXX puan veya SL yönünde ZZZ puan alındığında pozisyonu kapat **_-- _Böyle bir kural olmasıda anlamsızdır çünkü yine her durumda MinStdDev < MaxOfMinStdDev. Birçok grafik incelendi örnek olarakta aşağıdaki grafiği kopyalandı.__**

•	MinStddev (Kırmızı) ile MaxOfMinStdDev (Yeşil) arada YYY kadar fark olduğunda izlemeye al **_-- Birçok grafik incelendiğinde yukarı giden piyasa da sürekli bu iki çizgi eşitlenip uzaklaşıyor bu yüzden buradan bişey çıkacağını göremiyorum._**

•	MinStdDev = MaxOfMinStdDev olduğunda ve TP yönünde XXX puan alındığında pozisyonu kapat **_-- İlk kural ile farkını göremedim. Yukarı giden piyasada sürekli bu iki çizgi birbirine yapışıp birbirinden ayrılmaktadır bu yüzden işe yarayacağını düşünmüyorum. Birçok grafik incelendi örnek olarakta aşağıdaki grafiği kopyalandı_**

![image](https://user-images.githubusercontent.com/23281592/53834144-56c8ed00-3f9b-11e9-8686-da1a44ad077d.png)

**Comment by erkannurel** [comment]
Aşağı Yönlü Piyasa

SHORT pozisyonu için
•	MaxStdDev (Turkuaz) ile MinOfMaxStdDev (Mor) arada fark YYY puan olduğunda izlemeye al **_-- Birçok grafik incelendiğinde aşağı giden piyasa da sürekli bu iki çizgi eşitlenip uzaklaşıyor bu yüzden buradan bişey çıkacağını göremiyorum._**
•	MaxStdDev = MinOfMaxStdDev olduğunda ve TP yönüne XXX puan alındığında pozisyonu kapat **_-- Yukarıdaki bir önceki yorumumdaki mantık aynı şekilde burada da geçerlidir. Piyasa aşağı inmeye başladığında zaman zaman MaxStdDev = MinOfMaxStdDev zaman zaman birbirinden uzaklaştığı gözlenmiştir. Bu madde ile ilgili de bir çok grafik incelendi durumun değişmediği görülmüştür._**

![image](https://user-images.githubusercontent.com/23281592/53835881-8d086b80-3f9f-11e9-97e3-b2c6885603d4.png)

**Comment by erkannurel** [comment]
Benim bu konu için paylaşacaklarım bu kadardır. Eğer ekleyecek bir şeyin yok ise bu ticket'ı kapatmayı öneriyorum.
