### ISSUE TITLE
MaxOfMinStdDev ile MinOfMaxStdDev kesişmesi TP/SL kuralı

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#361]
Aşağı Yönlü Piyasa
SHORT pozisyonu için
•	MinOfMaxStdDev(Mor) yukarıdan aşağıya MaxOfMinStdDev (Yeşil) kesmişse ve aralarında fark XXX puan olursa pozisyonu kapat
•	Aşağı yönlü piyasada SHORT sinyali vermişsek, MinOfMaxStdDev(Mor) yukarıdan aşağıya MaxOfMinStdDev (Yeşil) kesmişse ve 3. basamak olursa pozisyonu kapat (Basamaklar Turkuaz ve Mor ayrıldığı yerlerde +1 sayılacak)

LONG pozisyonu için
•	MinOfMaxStdDev(Mor) yukarıdan aşağıya MaxOfMinStdDev (Yeşil) kesmişse SL ile kapat

**Comment by erkannurel** [comment]
Bir çok grafik incelemesi sonucunda standart sapmada lag olmasından dolayı kesişmeler pozisyon kapatıldıktan sonra gelebilmekte bu yüzden çok işe yarayacağını düşünmüyorum.

**Comment by erkannurel** [comment]
Yukarıda yazılan kuralara göre bir çok gün incelendi. Kesinlikle eminim pozisyon açıldıktan sonra terse bile gitse ya normalden daha geç kapatıyor veya hiç bir mor ve yeşil çizgilerde kesişim olmuyor. 

İkinci kere inceledim ikisinde de hiç bir sonuç alamadım bu yüzden konuyu kapatıyorum.
