### ISSUE TITLE
Araştır: Vortex based on mathematics

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#362]

**Comment by erkannurel** [comment]
Excel'deki örneğe göre piyasada uyarlayamaz mıyız? Yaptığım fiyattaki tüm basamakları topluyorum ve sonrasında çıkan sonucunda basamaklarını toplayıp tek haneli bir rakam elde ediyorum. Bu çıkan tek haneli rakamları vortex'de sanırım aşağı mı yukarı mı bir çizgisi vardı. Böyle yaparak bişey çıkaramaz mıyız? Örnek olsun diye bir excel hazırladım ek'te. 

[Vortex Örnek.xlsx](https://github.com/boratuncer/vobalgo/files/1525246/Vortex.Ornek.xlsx)

**Comment by boratuncer** [comment]
Test yaptığın gün hangisi ?

**Comment by erkannurel** [comment]
29.09.2017

**Comment by boratuncer** [comment]
3 SHORT, 6 LONG, 9 CLOSE yapabiliriz veya benzeri 9 LONG, 6 SHORT vs..

[Vortex-150730.xlsx](https://github.com/boratuncer/vobalgo/files/1526367/Vortex-150730.xlsx)

**Comment by erkannurel** [comment]
Deneyebiliriz bence güzel bir fikir sonra pozisyon açılışlarımız ile karşılaştırırız. Pozisyon açıldığında Kaç tane SHORT kaç tane LONG varmış ve sonrasında ne sinyal gelmiş karşılaştırma yapılabilir.

**Comment by erkannurel** [comment]
Çözülemedi.
