### ISSUE TITLE
Derece İle İlgili Algoritma

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#383]
1. Algoritma başlangıçta AVIHL ile açılacak.
2. Günün yükseğinden (veya xx kadar uzaklıkta yüksekten) aşağı doğru belli bir derece ile çizgi çizilecek.
3. Günün düşüğünden (veya xx kadar uzaklıkta düşükten) yukarı doğru belli bir derece ile çizgi çizilecek. 
4. Fiyat ile kesişimlerine bakılıp üzerinde tartışılacak.
5. Short pozisyonlarda madde 2'e bakılıp fiyat ile kesişimlerine bakılıp karar verilecek. 
6. Long pozisyonlarda madde 3'e bakılıp fiyat ile kesişimlerine bakılıp karar verilecek. 

Not: Bu algoritma özellikle V shape günlerde işe yaraması umulmaktadır. Ayrıca, AVIHL ile yanlış açılan pozisyonların çabuk kapatacağı hedeflenmiştir.

**Comment by boratuncer** [comment]
[150714.xlsx](https://github.com/boratuncer/vobalgo/files/1541642/150714.xlsx)

**Comment by erkannurel** [comment]
Düşünüldüğü gibi implemente edilemedi.
