### ISSUE TITLE
CP Kuralı Gözden Geçirilecek

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#384]

**Comment by boratuncer** [comment]
CP kuralı ve GünSonu maillerini atan kod bölümü bir timer altında her 5 dk'da bir çalışacak şekilde ayarlanmıştı. Çalıştığında da Ayarlar penceresi altında GünSonu değeri ile belirlenen değer ile bundan 9 dk sonrası arasında olup olmadığını kontrol ediyor ve buna göre işlem yapıyor.

Burada problem uygulamanın başlangıç süresi ile başlıyor. Eğer program örneğin 09:00:00'da başlatılmış ise 09:05:00 ..... 18:15:00 da çalışacaktır.


Yeni uygulamada ise bu timer yine 5'er dk'da bir çalışıyor ama saat 18:00:00'ı geçtiği zaman timer'ın çalışması 1dk'da bir olacak şekilde yeniden düzenleniyor.

Yine de kontrollü olmak amacıyla Ayarlar menüsü altında GünSonu değeri piyasa kapanış saatinden en az 5-6 dk öncesine ayarlanması önerilir.
