### ISSUE TITLE
Test: T. Hacim'i yükseltirsek Toplu Testlerde Sonuç Ne olur?

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#386]

**Comment by erkannurel** [comment]
Testler yapıldı tahmin edildiği gibi t. hacim yükseldikce brüt ve net kar düşmekte. 

[#386 T. Hacim'i yükseltirsek Toplu Testlerde Sonuç Ne olur.xlsx](https://github.com/boratuncer/vobalgo/files/1541496/386.T.Hacim.i.yukseltirsek.Toplu.Testlerde.Sonuc.Ne.olur.xlsx)

**Comment by boratuncer** [comment]
[VIHL Sabit TP.xlsx](https://github.com/boratuncer/vobalgo/files/1563674/VIHL.Sabit.TP.xlsx)

**Comment by boratuncer** [comment]
![image](https://user-images.githubusercontent.com/19672389/34058630-c65585d8-e1ec-11e7-8436-d57120282a9f.png)

**Comment by boratuncer** [comment]
520 günde yaklaşık 40bin puan ne kazancı var
