### ISSUE TITLE
AVIHL Algoritması Problemli Açılışlarına Çözüm Bulunacak 

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#389]
Gereksiz AL, SL sinyalleri azaltabilmek için açılışlara bir çözüm bulunmaya çalışılacak.

**Comment by boratuncer** [comment]
Bu konuda bir gelişme var mı ? Yoksa Won't Fix diyerek kapatalım mı ?

**Comment by erkannurel** [comment]
Çözülemedi.
