### ISSUE TITLE
Sinyal mailleri içeriğinde görsel düzenleme

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#396]
Sinyal maili içeriğinde görsel düzenleme yapılarak göze daha hoş olması sağlanacak

**Comment by erkannurel** [comment]
Siyah-Mavi olan başlıklar Mavi-Beyaz olarak değiştirilecek.

**Comment by boratuncer** [comment]
İlgili değişiklik yapıldı.
