### ISSUE TITLE
Ayarlar Açılış Hatası

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#40]
Programda ayarlara girdiğimizde "Aday Bilgileri" aşağıda gözüküyor. Ekran görüntüsünü yükledim. 
![ayarlar acilis hatasi](https://cloud.githubusercontent.com/assets/23281592/21343383/13c92f6e-c69f-11e6-8198-5091bf953a16.png)

**Comment by boratuncer** [comment]
Problem çözüldü.
