### ISSUE TITLE
TP(X) günleri için bir algoritma

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#413]
1) İlk TP'de iki pozisyon arasında X kadar tick varsa algoritmayı çalıştır
2) Eğer aynı yönlü pozisyon açılmak isteniyorsa Y kadar tick varsa pozisyon açmasına izin verme
3) Eğer ters yönlü pozisyon açılırsa arada Z kadar tick varsa pozisyon açmasına izin ver

**Comment by boratuncer** [comment]
Uygulaması şöyle oldu:
1. İlk TP'de pozisyon açılma ve kapanma noktaları arasında 4000 tick varsa algoritmayı çalıştır
2. Aynı yönlü pozisyon açma sinyali gelmişse ve ilk pozisyon açma ve kapama arasında 5000'den fazla tick varsa sinyali iptal et
3. Ters yönlü pozisyon açma sinyali gelmişse, sinyalin geldiği tick ile TP'nin kapanma tick'i arasında 4000tick ve üstü varsa terse pozisyon açmak için sinyali iptal et
4. İkinci, üçüncü pozisyonlar için çalıştırmıyoruz.


V0.6.4'te 520 gün için alınan toplam kar aşağıdaki gibiyken:
Toplam | 102,665 | İşlem | 1986 | Kar | 53,015 |  

Bu yeni algoritma ile toplam kar aşağıdaki gibi oluyor
Toplam | 105,71 | İşlem | 1964 | Kar | 56,61 |

**Comment by boratuncer** [comment]
Test sonuçları aşağıdadır.

[TP Günlerinde terse pozisyon algoritması.xlsx](https://github.com/boratuncer/vobalgo/files/1594236/TP.Gunlerinde.terse.pozisyon.algoritmasi.xlsx)

**Comment by boratuncer** [comment]
#region ALGO (#413) : TP(X) günleri için bir algoritma
                        if (this.al0051Enable == false)
                        {
                            if ((this.al0051I1 == 0) && (catchDataList[i].Count == 1))
                                this.al0051I1 = item.id;

                            if ((this.al0051I2 == 0) && (catchDataList[i].Count == 2))
                                this.al0051I2 = item.id;

                            if ((catchDataList[i].Count == 2) && (catchDataList[i][catchDataList[i].Count - 1].reason == reasons.tp) &&
                                ((this.al0051I2 - this.al0051I1) > 5000))
                                this.al0051Enable = true;
                        }

                        if (this.al0051Enable)
                        {
                            if (catchDataList[0][0].status == ret)
                            {
                                if ((this.al0051I2 - this.al0051I1) > 5000)
                                    ret = alarms.none;
                            }
                            else if (catchDataList[0][0].status != ret)
                            {
                                if ((item.id - this.al0051I2) > 4000)
                                    ret = alarms.none;
                            }
                        }
                        #endregion

**Comment by boratuncer** [comment]
Yeni implementasyon ve yeni sonuçlar

[TP Günlerinde terse pozisyon algoritması.xlsx](https://github.com/boratuncer/vobalgo/files/1594720/TP.Gunlerinde.terse.pozisyon.algoritmasi.xlsx)

**Comment by erkannurel** [comment]
Ellerine sağlık. Algoritmamıza ekleyelim.

**Comment by boratuncer** [comment]
Eklendi.
