### ISSUE TITLE
T.Hacim negatif iken artan piyasa için sinyal üretilmesi

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#414]
T.Hacim negatifte seyrederken piyasa yukarı gittiği durumlar oluyor, burada LONG sinyali verip kısa bir TP ile kapatmak gerekiyor.

Örnek gün olarak 150818'e bakılabilir, bu gün 400 tick civarında LONG vermek ve 4000 tick civarı kapatabilmek gerekiyor.

**Comment by erkannurel** [comment]
Şu şekilde sinyal verdirebiliriz: 

** T. hacim eksi tarafta ise ve LONG için fiyat yükseğe eşit ve pembe çizginin (minofms) üzerinde ise  pozisyon aç. TP: sabit 0.50 puan; SL: AVIHL standart kapanma koşulu 

** VEYA T. hacim eksi tarafta ise ve LONG için fiyat sadece pembe'nin üzerinde ise pozisyon aç. TP: sabit 0.50 puan; SL: AVIHL standart kapanma koşulu

**Comment by boratuncer** [comment]
** T. hacim eksi tarafta ise ve LONG için fiyat sadece pembe'nin üzerinde ise pozisyon aç. TP: sabit 0.50 puan; SL: AVIHL standart kapanma koşulu

[#414.xlsx](https://github.com/boratuncer/vobalgo/files/1602934/414.xlsx)

**Comment by erkannurel** [comment]
Sonuçlar kötüleşmiştir.
