### ISSUE TITLE
İlk açılan pozisyon için optimizasyon

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#415]
İlk açılacak pozisyon;
- LONG ise o an ki fiyat ile Düşük ile arasında X kadar fark varsa iptal et
- SHORT ise Yüksek ile o an ki fiyat arasında X kadar fark varsa iptal et

Güncellenmiş yeni hali aşağıdaki gibidir;

İlk açılacak pozisyon;
- LONG ise o an ki fiyat ile Düşük ile arasında 1000 kadar fark varsa iptal et ama aynı yönde 400 puan daha devam ederse LONG sinyali ver
- SHORT ise Yüksek ile o an ki fiyat arasında X kadar fark varsa iptal et ama aynı yönde 400 puan daha devam ederse SHORT sinyali ver
- Algoritma çalışmış ise tek TP'den sonra yeni pozisyon açmasına izin verme

**Comment by boratuncer** [comment]
İlk testlerde aşağıdaki gibi implemente edince 520 gün için yaklaşık 2500 puan kazancımız var.
- LONG ise o an ki fiyat ile Düşük ile arasında 1000 puan kadar fark varsa iptal et
- SHORT ise Yüksek ile o an ki fiyat arasında 1000 puan kadar fark varsa iptal et
 
 
V0.6.5 sonuçları
Toplam | 106,13 | İşlem | 1972 | Kar | 56,83 |  

Algoritma sonuçları
Toplam | 107,55 | 1930 | İşlem | Kar | 59,3 |  

Toplamda 13 günü etkiliyor, fakat algoritmada büyük bir problem var, gün boyunca sinyal açmasını engelliyor. Buna çözüm eklemek gerekiyor.

Çünkü sinyal düşmeye veya yükselmeye devam ediyorsa normal zamanda almamız gereken kar'ı kaçırıyoruz. Örneğin sadece 25.07.2016, 09.11.2016, 25.09.2017 günlerinde yaklaşık 3000 puan kaybediyoruz, bunları da almış olsaydık algoritmanın kar'ı 5000 puanı aşacak

**Comment by boratuncer** [comment]
Algoritma'da sonlandırma tarafı da eklendi. 1000 puan'dan sonra halen 400 puan daha anı yönde devam ediyorsa bu yönde sinyali otomatik açma bölümü eklendi.

**Comment by boratuncer** [comment]
Test sonuçları aşağıdaki gibidir.

[İlk pozisyon için geliştirme.xlsx](https://github.com/boratuncer/vobalgo/files/1596411/Ilk.pozisyon.icin.gelistirme.xlsx)

**Comment by erkannurel** [comment]
Eklenebilir. Kayıplar küçük kazançlar büyük görünüyor.

**Comment by boratuncer** [comment]
İlgili algoritma sisteme eklendi.

**Comment by boratuncer** [comment]
Algoritma aşağıdaki gibi değiştirildi;
1. a) Sinyal LONG ise, o an ki fiyat ve low arasında 1000 puan ve üstü fark varsa fiyatı kayıt et ve sinyali iptal et
   b) Sinyal SHORT ise, o an ki fiyat ve high arasında 1000 puan ve üstü fark varsa fiyatı kayıt et ve sinyali iptal et

Eğer 1.a) kuralı gerçekleşmiş ise;
 i) Eğer fiyat kayıt edilen fiyatı 0.4 puan geçmişse LONG sinyal ver
 ii) O an ki fiyat ve low arasında 1200 puan ve üstü far varsa LONG sinyal ver
 iii) Eğer fiyat low'a eşit ve hacim pozitif taraftaysa LONG sinyal ver

Eğer 1.b) kuralı gerçeklemiş ise;
   i) Eğer fiyat kayıt edilen fiyatın 0.4 puan aşağısına inmiş ise SHORT ver ve local min. için TP'yi fiyat - 0.4 olarak kayıt et
   ii) O an ki fiyat ve yüksek  arasında 1800 puan ve üstü varsa SHORT sinyal ver ve local min. için TP'yi fiyat - 0.4 olarak kayıt et
   iii) Eğer fiyat local min. altına düşerse yeni local min olarak kayıt et.
   iv) Eğer fiyat local min. 100 puan üstüne çıkarsa pozisyonu TP ile kapat


Eğer pozsiyon TP ile kapatılmışsa başka sinyal verme.
