### ISSUE TITLE
2018 senet isimleri programda DNC altına girilecek

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#416]
Hocam senet isimlerini bulduktan sonra bana assign edersen hemen koda ekleyeyim.

**Comment by erkannurel** [comment]
F_XU0300218 
F_XU0300418
F_XU0300618
F_XU0301218

**Comment by boratuncer** [comment]
Hangi tarihler arasında geçerliler ? Birde toplamda 6 senet olması lazım değil mi ?

**Comment by erkannurel** [comment]
F_XU0300218  --- 01/01/2018 - 28/02/2018
F_XU0300418  --- 01/03/2018 - 30/04/2018
F_XU0300618  --- 01/05/208 - 30/06/2018
F_XU0300818 --- 01/07/2018 - 31/08/2018  
F_XU0301018 --- 01/09/2018 - 31/10/2018
F_XU0301218  --- 01/11/2018 - 31/12/2018

_Not: Bir önceki comment'te kontrat isimleri eksik yazılmış._

**Comment by boratuncer** [comment]
İlgili değişiklik yapıldı.
