### ISSUE TITLE
Gün Sonu : 2018.01.02 Mailinde Eksik Bilgi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#418]
Aracı Kurum Kontrat Hareketlerinde aşağıdaki 4 kontratlık işleme ek olarak 1 kontratlık daha işlem olmuştur ama mailde gözükmemektedir. 

Emir | Fiyat | Adet
**Al Sinyali | 146,675 | 4**
Sat Sinyali | 147,875 | 5
Al Sinyali | 148,025 | 5
Sat Sinyali | 148,075 | 5

![image](https://user-images.githubusercontent.com/23281592/34499066-60c7e4d6-f015-11e7-8c01-7dae8a84c6e4.png)

**Comment by boratuncer** [comment]
InvestAZ'den önceki gün'e ait "0" değerli veriler geldiği ve bunun gösterilmemesi istenen bug için yapılan değişiklik bu probleme neden oldu, ilgili kod değiştirildi.
