### ISSUE TITLE
Günün Analizi: 180103

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#421]
3 Ocakta sabah 10:00'da enflasyon verisi açıklanacaktı. Veri açıkladığında aslında beklentiden kötü geldi özellikle çekirdek enflasyon (piyasa tarafından önem verilir) yüksek geldi, 12.3%. Bizim algoritmamızda saat 10:04'te short sinyali verdi bu veriye dayanarak. Kısa bir süre sonra toparladı ve yukarı gitmeye başladı. 

Short sinyalinden sonra yukarı gitmeye başladığında minofms çizgisini geçerken (1135. tick itibariyle) kapatıp yukarı terse pozisyon açsaydık 1000 puanlık bir kar potansiyelimiz olacaktı. Normal algoritma kapattığı seviyede de 575 puan alabilirdik. İlk açtığımız pozisyonu da erken kapatmış olacaktık (250 puan zarar). 

Daha sonra piyasa bir aşağı bir yukarı yapıyordu. Algoritmamızda bir long sinyali verip bunu zarar ile kapatıyor. Pozisyonumuz kapandıktan sonra kısa bir süre sonra piyasa aşağı gelmeye devam ediyor. Bu düşüşü de şu şekilde yakalabilirdik: Fiyat yine minofms'in altına geliyorsa short pozisyonu aç. Söylediğim nokta 7321. satır. CP ile kapandığını varsaysak 1250 puan gelir yazabilirdik. 

Yukarıda anlattığım senaryolar henüz toplu olarak izlenmemiştir. Günün grafiği ve log dosyası aşağıdadır. 

![180103](https://user-images.githubusercontent.com/23281592/34583079-4f511004-f1a7-11e7-9872-d319993bcfc6.jpg)

[VOBALGO_Data_180103.log](https://github.com/boratuncer/vobalgo/files/1604641/VOBALGO_Data_180103.log)

**Comment by boratuncer** [comment]
Algoritma tam olarak nasıl olacak ?

SHORT için fiyat minofms'yi yukarı yönlü keserse SL ile mi kapatıp, LONG pozisyon açacağız ?

**Comment by erkannurel** [comment]
#437 Testi yapılmıştır zarar edildiği anlaşılmıştır.
