### ISSUE TITLE
Günün Analizi: 180104

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#422]
Piyasa ani açılışından 4 saniye sonra short sinyali aldık ve hiç aşağı gelmeden yukarı gitmeye başladı. Biz yine burada fiyat minofms'nin üzerine çıkarken pozisyonumuzu kapatıp terse pozisyon açmış olsaydık. 761. satırdan bahsediyorum zararımız 425 puan olacaktı ve erken pozisyon açmış olacaktık. Bu erken pozisyon ile kar potansiyelimiz 1875 puan olacaktı. Şayet algoritma standart kapanmasınıda yapsa bile 1000 puan karı var. 

Bir önceki gün gibi biraz aşağı biraz yukarı gitmeye devam ediyor. Saat 16:15'de USA ADP Employment datası ile aşağı gelmeye başlıyor ve 16:40'da minofms çizgisininde altına gelmeye devam ediyor (11192. satır). Şayet burada bile girmiş olsaydık 1000 puanın üzerinde kar potansiyelimiz olacaktı. 

Günün grafiği ve log dosyası aşağıdadır. 

![180104](https://user-images.githubusercontent.com/23281592/34583803-2520e676-f1aa-11e7-9d9b-f3081e6b122a.jpg)

[VOBALGO_Data_180104.log](https://github.com/boratuncer/vobalgo/files/1604674/VOBALGO_Data_180104.log)

**Comment by boratuncer** [comment]
4. saniye'de herhangibir sinyal vermek çok mantıklı değil, log inceleme yaptığımızda T.Hacim -558'de SHORT vermiş, bu bir bug olabilir

**Comment by boratuncer** [comment]
7 | 09:30:04 | 145,000 | Alış | 330 | 366.851 | 145,700 | 145,000 | -558 | 0,000000 | 0,000000 | 0,000000 | 0,000000
6 | 09:30:03 | 145,000 | Satış | 814 | 366.851 | 145,700 | 145,000 | -888 | 0,000000 | 0,000000 | 0,000000 | 0,000000

6. tick'te biri 814 lot satmış, doğal olarak bizim algoritmada 7. tick'te short vermiş. İstersen buna bir önlem koyalım, mesela ilk 20 tick'te sinyal verme vs.. ?

**Comment by boratuncer** [comment]
Test sonuçları ektedir.

[#422.xlsx](https://github.com/boratuncer/vobalgo/files/1605772/422.xlsx)

**Comment by erkannurel** [comment]
Koda ekleyelim lütfen. 40 tick.

**Comment by boratuncer** [comment]
Koda eklendi.
