### ISSUE TITLE
X Tick Kadar Fiyat Değişimi Bakılarak Hız Ölçümü

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#424]

**Comment by boratuncer** [comment]
520 günde 1500 puan gibi bir getirisi oldu, pek efektif değil.

[424.txt](https://github.com/boratuncer/vobalgo/files/1617494/424.txt)

**Comment by boratuncer** [comment]
Yanlış bug için comment girildi, comment'leri düzeltiyor ve bug'ı tekrar açıyorum.

**Comment by boratuncer** [comment]
Bu konuda bir gelişme var mı ? Yoksa Won't Fix diyerek kapatalım mı ?

**Comment by erkannurel** [comment]
Çözülemedi.
