### ISSUE TITLE
"Log İnceleme Sırasında Log Almayı Bırak" Seçeneğini Seçtiğimde Canlı Log Almıyor

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#429]
Kişisel ayarlar altında "Log inceleme sırasında log almayı bırak" seçeneğini seçtiğimizde ve canlı log almak istediğimizde log alamıyoruz. 

Bu seçeneğin sadece testler yaparken log aldığımızda çalışması gerekmez mi?

**Comment by boratuncer** [comment]
Problemi yaratamıyorum. Aşağıdaki adımları izledim;

1. Ayarlar altında "Log inceleme sırasında log almayı bırak" seçeneğini aktif hale getirdim.
2. Log iceleme yaptım, log almadığını gördüm
3. DDEServer kullanarak veri bağlantısı kurdum, bu süre içinde log almaya başladı

**Comment by erkannurel** [comment]
12 Ocak tarihinde V.0.6.5 ile ev'den log almıştık. Log dosyasına baktığımda 1kb gözükmekte ve İş pc'imden program farklılıklarına bağtığımda. "Log inceleme sırasında log almayı bırak" seçeneğinin seçili olduğunu gördüm (Evde sürekli log inceleme yapmamdan dolayı bunu sürekli yaparım). 

Ayrıca, error dosyasında da hiç bir şey yok.

**Comment by boratuncer** [comment]
Yukarıda anlattığım şekilde tekrar deneyebilir misin ? Eğer aynı sorunu yaşıyorsan yine bakalım, yoksa ticket'ı tekrar benzer sorunu yaşayana kadar kapatırız.

**Comment by boratuncer** [comment]
Test yapabilme şansın oldu mu ?

**Comment by erkannurel** [comment]
Log kaçırmayı göze alamadığım için deneyemiyorum.

**Comment by boratuncer** [comment]
Ticket'ı geçici olarak kapatıyorum, bir daha yaşarsak tekrar inceleriz.
