### ISSUE TITLE
Short Pozisyonları İçin Pembe Çizgi Algoritması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#437]
* ilk iki pozisyon zarar ile kapanması gerekiyor
* İkinci pozisyonun kapanışı pembe çizgi üstünde gerçekleşmesi gerekiyor.
* fiyat yukardan aşağıya pembe çizgiyi kestiğinde short sinyali açılacak
* 800 puan kuralı disable edilecek
* pozisyon açıldıktan sonra   standart algoritma kapatma kurallarımız çalışacak??? Veya
* zararımız kadar kar alınıp   pozisyon kapatılacak???
* kar veya zarardan sonra tekrar   pozisyon açılmayacak.
* 16:45 kuralı disable

**Comment by erkannurel** [comment]
Algoritmada etkileyen günler incelediğinde toplamda 2375 puan zarar yazılmıştır. Bu yüzden implemente edilmeyecektir. 

[#437 Short Pozisyonları İçin Pembe Çizgi Algoritması.xlsx](https://github.com/boratuncer/vobalgo/files/1642699/437.Short.Pozisyonlari.Icin.Pembe.Cizgi.Algoritmasi.xlsx)

**Comment by erkannurel** [comment]
Ocak ayında 600 puan düzeltildi. Bu yüzden sana bırakıyorum kod tarafını. İstediğim sonucu ben alamadım. 

[#437 Short Pozisyonları İçin Pembe Çizgi Algoritması (Ocak Ayı Testi).xlsx](https://github.com/boratuncer/vobalgo/files/1740605/437.Short.Pozisyonlari.Icin.Pembe.Cizgi.Algoritmasi.Ocak.Ayi.Testi.xlsx)

**Comment by boratuncer** [comment]
Bu konuda nasıl devam edelim ?

**Comment by erkannurel** [comment]
Yukarıda da yazdığım gibi istediğim sonucu alamadım bu yüzden konuyu kapatıyorum.
