### ISSUE TITLE
Erken açılan SHORT yönlü ilk pozisyonun AL ile kapanmaması için optimizasyon

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#439]
Erken sinyal verdiğimiz zamanlarda çoğunlukla ilk pozisyon AL ile kapanıyor, bunu önlemek için bir algoritma yazılacak

**Comment by boratuncer** [comment]
Algoritma aşağıdaki gibidir;

1. İlk 300 tick ile 1300 tick arasında çalış
2. İlk pozisyon sadece aşağı yönlü ise çalış
3. Eğer pozisyon kapatma isteği AL nedeniyle geliyor ve pozsiyon açılan maxofminstddev ile o an ki maxofminstddev aynı ise (max. 0.025 puan fark aynı kabul ediliyor), pozisyonun AL ile kapanmasına izin verme
4. Eğer 3. koşul bir kere bile gerçekleşmiş ise aşağıdaki procedürü çalıştır.
    a) Eğer sinyal açıldığı sıradaki fiyat minofmaxstddev'in altında ise ve şimdiki fiyat şimdiki minofmaxstddev'in 0.025 puan üzerindeyse otomatik olarak pozsiyonu AL ile kapat

**Comment by boratuncer** [comment]
Yukarıda ki algoritmaya ek olarak aşağıdaki özel kural yazıldı; 

5. Eğer 1) ve 2) adım gerçeklemiş ise ve fiyat o an ki minofmaxstddev'i geçmiş ise ve ilk pozisyon açılan tick 500'den önce ise ve pozisyon açılan fiyat pozisyon açıldığı anda minofmaxstddev'in ve maxofminstddev'in altında ise pozisyonu kapat

**Comment by boratuncer** [comment]
Test sonuçları aşağıdaki gibidir;

[#439.xlsx](https://github.com/boratuncer/vobalgo/files/1653455/439.xlsx)

Uygun dersen hemen ekleyelim.

**Comment by erkannurel** [comment]
Uygun.

**Comment by boratuncer** [comment]
Algoritma eklendi.
