### ISSUE TITLE
üçüncü poz. Local max testi 

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#440]

**Comment by boratuncer** [comment]
İşlem yapılan bütün günlerde bize zarar veriyor, tek yolu işlem yapılmaması.

[440.txt](https://github.com/boratuncer/vobalgo/files/1658557/440.txt)

[#440.xlsx](https://github.com/boratuncer/vobalgo/files/1658558/440.xlsx)

**Comment by boratuncer** [comment]
Uygulama eklenmedi.
