### ISSUE TITLE
Maxofms ile Minofms kesişmesinde ilk long pozisyonu yukarı yönlü ise ne yapabiriz?

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#441]
![image](https://user-images.githubusercontent.com/23281592/35225894-9270494e-ff9a-11e7-809a-00ae98ee1f11.png)

**Comment by erkannurel** [comment]
İlk gözlemlere göre CP'li günlerde erken kapatıyor.

**Comment by boratuncer** [comment]
Bu konuda nasıl devam edelim ?

**Comment by erkannurel** [comment]
Genelinde iyi bir sonuca varamadım. Bu yüzden kapatıyorum.
