### ISSUE TITLE
25.09.2017 tarihinde neden algoritma çalışmıyor?

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#442]
25.09.2017 tarihinde 980. satırda Short sinyali gelmesi gerekirken gelmediğini farkettim. Sence neden?

**Comment by boratuncer** [comment]
#415 nolu ticket için geliştirilen algoritma yüzünden pozisyon açılmamış. Yaklaşık 1000 puan kaybetmişiz.

#415 çalışmadığı durumda alınan sinyaller.
Al Sinyali : 11:59:22 - 127,700 - TP
Sat Sinyali : 10:00:31 - 128,725 - AL

573 günlük testlerin sonucunda #415 algoritması  Brüt : 2,889 puan, Net : 3,839 puan kazandırıyor.

25.09.2017 gününde de #415 nolu algoritmanın ikinci kısmında 400 puan koruması çalışması gerekirken çalışmamış, bu yüzden hiç sinyal açmamış, bunun düzeltilmesi gerekiyor.

**Comment by boratuncer** [comment]
Güzel sonuçlar var, gecenin ilerleyen saatlerinde paylaşacağım.

**Comment by boratuncer** [comment]
Kodda bulunan yanlışı düzelttim, 4.000 puan extra daha kazandırdı. Böylece #415 algoritması toplamda 7300 puan kazandırıyor

[#442.xlsx](https://github.com/boratuncer/vobalgo/files/1692294/442.xlsx)

**Comment by boratuncer** [comment]
Problem çözüldü.
