### ISSUE TITLE
Günsonu mailinde hata

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#445]
24.01.2018 tarihli gün sonu mailinde aracı kurum kontrat hareketlerinde gün içinde emir göndermesine karşı mailde yazmamıştır.

**Comment by boratuncer** [comment]
Aracı kurum yüzünden olduğunu düşünüyorum, ilgili fonksiyona try-catch yapısı ekledim, tekrarlarsa problemin asıl kaynağını bulabileceğiz.

**Comment by boratuncer** [comment]
V0.6.6.d sürümüne yukarıda belirtilenler eklendi, hatanın tekrarlanması bekleniyor. Tekrarlanırsa ilgili error log'ları ile birlikte bu ticket'ı açalım.
