### ISSUE TITLE
Türev Alma

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#450]

**Comment by erkannurel** [comment]
((X*(t+1)-X*(t-1))/2t formülüne göre excel de denemeler yapılmıştır. Fiyat aşağı veya yukarı gitmiş olsa bile hesapladığımız rakam sürekli 0'a doğru küçülmektedir. Bu yüzden bir sonuca varılamamıştır.

[#450 Türev Alma.xlsx](https://github.com/boratuncer/vobalgo/files/1715695/450.Turev.Alma.xlsx)

**Comment by boratuncer** [comment]
Amaç zaten sıfıra doğru gitti noktada tepeyi yakalamak, bununla ilgili bir çalışma paylaşacağım.

Bu testleri yapmadan önce line smoothing yaptın mı ?

**Comment by erkannurel** [comment]
Yok yapmadım direk anlık fiyat üzerinden gittim.

**Comment by boratuncer** [comment]
Üzerinde gürültü bulunan tüm veriler önce bir filitreleme yöntemi ile pürüzsüzleştirilmesi gerekiyor. Bunun için Kalman Filitresi kullanmanı öneririm ama olayı kavramak açısından önce MeanOfTree ile de smoothing yapabilirsin.

Bu arada excell'i kontrol ettim, türev almak için kullanılan formülde yanlış. İnternette discrete derivation ile ilgili çok örnek var. Genel olarak t+1 de ki fiyat ile t-1 de ki fiyatı çıkarıp uzaklığa bölünecek.

**Comment by erkannurel** [comment]
Söylediğin şekilde denemeler yaptım. Çıkan sonuçların anlamlı olduğunu düşünmüyorum. Lütfen kontrol edebilir misin?

[#450 Türev Alma 2.xlsx](https://github.com/boratuncer/vobalgo/files/1726985/450.Turev.Alma.2.xlsx)

**Comment by boratuncer** [comment]
Daha sonra tekrar konu üzerinde araştırma yapılacak
