### ISSUE TITLE
İlk pozisyonların AL ile kapanmasını zorlaştıran bir algoritma

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#454]

**Comment by boratuncer** [comment]
Algoritma aşağıdaki şekilde uygulandı;

1. Sadece ilk pozisyonlar için;
   i) Pozisyon LONG ise, 150 tick'ten önceki pozisyon için AL ile kapanma hacimi -300, 150 tick'ten sonraki pozisyonlar için AL ile kapanma hacimi -1000
   ii) Pozisyon SHORT ise, 250 tick'ten önceki pozisyon için AL ile kapanma hacimi 300, 250 tick'ten sonraki poziyonlar için AL ile kapanma hacimi 1000

2.) Eğer 1) satır çalışmış ise, açılan ikinci pozisyon, 3000 tick boyunca kapanmamış ise TP ile kapatma, SL veya CP ile kapansın.

[#454.xlsx](https://github.com/boratuncer/vobalgo/files/1727768/454.xlsx)

**Comment by erkannurel** [comment]
Lütfen koda ekleyelim. Ellerine sağlık.

**Comment by boratuncer** [comment]
Algoritma koda eklendi.
