### ISSUE TITLE
Algoritma Denemesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#455]
Algoritmanın trigerını değiştirmek amacıyla AVIHL algoritmamızın TP veya SL alma kuralına göre pozisyon açılış ve kapanışları üzerine çalışmak:

1) SHORT sinyali için (hacim ne olursa olsun) turkuaz yeşili keserse sinyal ver.
2) LONG sinyali için (hacim ne olursa olsun) pembe kırmızıyı keserse sinyal ver.

Ters işaretler geldiğinde pozisyonu kapat terse pozisyon aç.

![capture](https://user-images.githubusercontent.com/23281592/36507610-4ffd7f80-176b-11e8-9ae1-e9b62583c21c.JPG)

**Comment by boratuncer** [comment]
Bu konuda nasıl devam edelim ?

**Comment by erkannurel** [comment]
Konu açık kalsın.

**Comment by boratuncer** [comment]
Bu konuda bir gelişme var mı ? Yoksa Won't Fix diyerek kapatalım mı ?

**Comment by erkannurel** [comment]
Çözülemedi.
