### ISSUE TITLE
Yüksek-Düşük Karşılaştırma Algoritması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#456]
Algoritma AVIHL şartları ile açıldıktan sonra;

LONG pozisyonlarında günün yükseği ile belli bir aralıktaki yüksek rakamı ile karşılaştırma yaparak gerekirse pozisyonu kapatacak.

SHORT pozisyonlarında günün düşüğü ile belli bir aralıktaki düşük rakamı ile karşılaştırma yaparak gerekirse pozisyonu kapatacak.

Testler sonucunda gerekirse terse pozisyon açılacak (veya bir condition daha eklenerek terse pozisyon açılacak).

**Comment by boratuncer** [comment]
Formülleri de yazabilir misin ?

**Comment by erkannurel** [comment]
Dosyanın içinde düşüncelerimi bulabilirsin. 

[#456 Yüksek-Düşük Karşılaştırma Algoritması.xlsx](https://github.com/boratuncer/vobalgo/files/1806318/456.Yuksek-Dusuk.Karsilastirma.Algoritmasi.xlsx)

**Comment by boratuncer** [comment]
Bu konuda nasıl devam edelim ?

**Comment by erkannurel** [comment]
Bu konuya ileride bakılmak üzere şimdilik kapatıyorum.
