### ISSUE TITLE
Günsonu maillerinde CP sinyaller gözükmüyor

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#459]
Gün sonu maillerinde aracı kurum kontrat hareketleri altında CP sinyali gözükmemektedir. Pozisyona baktığımda kapatılmış. Sadece mail de problem var.

**Comment by boratuncer** [comment]
CP sinyalinin arazı kuruma gönderilmesinden 5sn sonra gün sonu maili atılıyordu, sanırız aracı kurum bu 5sn'lik aralığa sığamıyor, bunu 60sn olarak güncelliyorum.

Gün sonu mailinin gönderildiğinin log'unu İletiler penceresinde görmeden programın kapatılmaması gerekiyor

**Comment by boratuncer** [comment]
İlgili çözüm koda eklendi.
