### ISSUE TITLE
T. hacim 4422'den başladı

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#460]
T. hacim 4422'den başladı. Neden olduğunu anlayamadım. Ekran görüntüsü aşağıda. 

![image](https://user-images.githubusercontent.com/23281592/37390867-7789d872-277a-11e8-874b-29d8f94f36ff.png)

**Comment by boratuncer** [comment]
settings.xml dosyasını da rica edebilir miyim ?

**Comment by erkannurel** [comment]
Mail gönderildi. Bu platformdan yüklenemedi.

**Comment by boratuncer** [comment]
Ayarlarda "useLastVolumeData" true olarak bırakılmış. Bunun false olması gerekiyor.

**Comment by erkannurel** [comment]
Yapıldı.
