### ISSUE TITLE
TP(AL/SL) günleri için aynı yönlü sinyallerde geliştirme

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#464]
TPAL ve TPSL günleri için bir pattern testi yapılacak. TP'den sonra aynı yönlü pozisyon açılmak isteniyorsa, önceki pozisyondan X kadar daha aynı yöne gitmişse pozisyon açılmasına izin vermemeyi düşünüyorum.

**Comment by boratuncer** [comment]
Algoritma da (X)TP(AL/SL) günleri için aksiyon alındı. Genel olarak TP ile kapanan ikinci pozisyondan sonra aynı yönlü tekrar pozisyon açmak istendiğinde belirli şartlarla buna izin veriyor.

1) Eğer (X)TP olmuş ve 3. pozisyon ikinci ile aynı yönle açılmak isteniyor ve ilk pozisyon 300 tick'ten sonra açılmış ise
   a) Eğer SLTP ile gelmiş ise ve 3. pozisyon 4500 tick'ten daha büyükse pozisyon açma
   b) Eğer ALTP ile gelmiş ise
        i) 3. pozisyon açılış fiyatı 2. pozisyon (TP ile) kapanış fiyatına eşit değil ise pozisyon açma
        ii) 3. pozisyon açılış fiyatı 2. pozisyon (TP ile) kapanış fiyatına eşit ise ve 1. pozisyon açma ve 3. pozisyon açma fiyatları arasında 0.7 puandan fazla fark varsa pozisyon açma

Eklenen kod aşağıdaki gibidir;

[#464.txt](https://github.com/boratuncer/vobalgo/files/1983726/464.txt)

2018 Q1 sonuna kadar olan günlerde yapılan testlerde toplamda 5,940 puan kazandırarak %9 civarı kar elde ettik. Detaylı gün analizi aşağıdadır.

[#464.xlsx](https://github.com/boratuncer/vobalgo/files/1983694/464.xlsx)

**Comment by boratuncer** [comment]
Koda ekleyelim mi ?

**Comment by erkannurel** [comment]
Olur.

**Comment by boratuncer** [comment]
Koda eklendi.
