### ISSUE TITLE
Toplu Test

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#468]
Elimizde bugüne kadar 35 aylık veri bulunmakta. Şu şekilde toplu test yapmak istiyorum: Örneğin 34 ayın en iyi AVIHL sonucunu bulup, 35. aya bu sonuç ile test edip sonucu bugun aldığımız 700/-700 sonucu ile karşılaştırmak istiyorum.

**Comment by erkannurel** [comment]
35. ayda sonuçlar iyi çıkıyor ama bence yanıltıcı. Örneğin aynı testleri 13.07.2015 - 29.12.2017 arasında da yapsak en iyi sonuç +700/-700 çıkıyor bu ikili ile devam ediyorsun sonraki 4 ayda zarar ediyorsun (-11.678 puan). Bu sefer 13.07.2015 - 30.04.2018 arasında en iyi sonucu bulmaya çalışıyorsun yine en iyi ikili +700/-700 çıkıyor. Bu durumda nasıl en iyi ikili +700/-700???

[#468 Toplu Test.xlsx](https://github.com/boratuncer/vobalgo/files/2108442/468.Toplu.Test.xlsx)

**Comment by boratuncer** [comment]
Bence bunu da adaptif yapmak için bir algoritma düşünmek lazım.

**Comment by erkannurel** [comment]
Şimdilik konuyu kapatıyorum ileride birşey bulursak tekrar konuyu açarız.
