### ISSUE TITLE
V.0.6.9 çalışırken kapanıyor

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#469]
Bugün iki sefer V.0.6.9 çalışırken kapandı. Fazla uzaktan bağlantı sağlayamadığım için takip edemedim. Tahminim emir gönderirken program kapanıyor. Error dosyası boş olduğu için ek'e koymadım. Ek'te emir gerçekleşme saatlerini ve logları incelediğinde göreceksin. 

[VOBALGO_Data_180529.log](https://github.com/boratuncer/vobalgo/files/2047193/VOBALGO_Data_180529.log)
![saatler](https://user-images.githubusercontent.com/23281592/40644891-5a685c70-632d-11e8-802b-ee8dfcd6640c.png)

**Comment by boratuncer** [comment]
Problem V0.6.9.a da çözüldü.
