### ISSUE TITLE
04-07 Haziran arası loglar eski sürümlerle tekrar incelenmesi

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#473]
Yeni eklenen algoritmaların 04-07 Haziran arası yanlış çalıştığını on görüyoruz, yeniden incelenmesi gerekiyor.

**Comment by erkannurel** [comment]
Eski versiyonlara göre baktığımızda V.0.6.7 sonraki algoritmalardan kaynaklanan fark olduğu görülmektedir. Sonuçları excel dosyasından karşılaştırabilirsin.

[#473 04-07 Haziran arası loglar eski sürümlerle tekrar incelenmesi.xlsx](https://github.com/boratuncer/vobalgo/files/2087419/473.04-07.Haziran.arasi.loglar.eski.surumlerle.tekrar.incelenmesi.xlsx)

**Comment by boratuncer** [comment]
V0.6.7 de düzgün, V0.6.8 de çalışmıyor diye anladım, doğru mu ?

**Comment by erkannurel** [comment]
Evet. 6 ve 7 Haziran'ı olumlu etkiliyor.

**Comment by boratuncer** [comment]
Bu haftanın loglarınıda rica edebilir miyim ? Testlerde ihtiyacım var.

**Comment by erkannurel** [comment]
Onedrive'a yüklendi.

**Comment by boratuncer** [comment]
07.06.2018
------------------------------
#449 nolu algoritma yüzünden kayıp yaşanıyor.

#449 aktifken sonuç
7.06.2018 | -2,956 | 2 | CP

#449 pasifken sonuç
7.06.2018 | 0,588 | 4 | ALCP

06.06.2018
------------------------------
#454 nolu algoritma yüzünden az kar yaşanıyor

#454 aktifken sonuç
6.06.2018 | 0,363 | 4 | SLCP

#454 pasifken sonuç
6.06.2018 | 2,213 | 4 | SLTP

**Comment by boratuncer** [comment]
06.06.2018'de #454'teki hata çözüldü, 13.07.2015 - 30.03.2018 arası testlerde sadece 0,35 puan kaybediyoruz, ama 06.06.2018'de algoritma düzgün çalışarak kapatması gereken yerde kapatıyor ve 2,213 puan kazanıyoruz.

İlgili yazılım OneDrive'a V0.6.9b olarak yüklendi.

07.06.2018'de olan #449 nolu algoritmada ki hata çözümü kolay değil, algoritma bu bile haliyle bize 26.000 puan kazandırıyor. 26.000 puan'dan vazgeçersek algoritmayı kapatıp V0.6.9c olarak yeni sürüm çıkarabilirim ??

**Comment by erkannurel** [comment]
Teşekkürler. 

07.06.2018 için #454 algoritmada son cümle şudur: 2.) Eğer 1) satır çalışmış ise, açılan ikinci pozisyon, 3000 tick boyunca kapanmamış ise TP ile kapatma, **SL veya CP ile kapansın**.

Yukarıdaki cümlede SL ile kapansın demişiz. 07.06.2018 tarihinde 2000 puandan fazla terse gidiyor ve SL yemiyoruz. Burada müdahale etmemiz gerekmez mi?

Ayrıca, 26,000 puan karı ben #454 excelde göremedim. 2018 yılı testleri de var? Bu konu da tekrar bir excel paylaşabilir misin?

**Comment by boratuncer** [comment]
07.06.2018 de #449 algoritması çalışıyor, son commemt'imde yanlışlıkla #454 yazmışım.

#454 nolu algoritma 06.06.2018 de çalışıyor ve hatası V0.6.9b sürümünde çözüldü.

#449'un da excel dosyası ticket içinde bulunuyor.

Önceki comment'imi düzeltiyorum.

**Comment by erkannurel** [comment]
V.0.6.9b ile test yaptığımda söylediğin gibi #449 algoritması çalışıyor. Ama sonrasında da TP alıyoruz. Yani algoritmayı pasif yapıp 26,000 puanı feda etmiyoruz. Ekran görüntüsü aşağıdadır: 

![image](https://user-images.githubusercontent.com/23281592/41281952-69965e54-6e3b-11e8-89a2-f2ce665bd854.png)

Ayrıca, #449 algoritması V.0.6.8'da çıkarıldı. V.0.6.7b ile toplu test yapıp karşılaştırdığımda 26,000 puan ekstra kazanç göremiyorum. Hem 29.12.2017 tarihine kadar hem de 30.04.2018 tarihine kadar ayrı ayrı testler yaptım. Bu konuda excel paylaşır mısın? Etkilenen günleri incelemek için bakmak istedim. Ben mi yanlış yapıyorum.  

[Test.xlsx](https://github.com/boratuncer/vobalgo/files/2094498/Test.xlsx)

**Comment by boratuncer** [comment]
V0.6.9b'de halen #449 algoritması etkin, yukarıda comment içinde eğer 26.000 puandan vazgeçersek #449'u kapatıp V0.6.9c çıkarabilirim diye yazmıştım.

Biz 2 kişi olduğumuz için iş yoğunluğunu azaltmak amacıyla hangi kulakçıklı sürümleri kayıt altına almadım, yani #449 algoritması V0.6.7'den sonraki sürümde çıktı ama V0.6.7a'da veya V0.6.7b de varmıydı hatırlamıyorum. Git üzerinde de kulakçıklı sürümleri yaratmadım, hep major V0.6.7, V0.6.8 gibi sürümleri kayıt altına aldım.

Log'lar #449 nolu ticket'ın içinde zaten yüklemiştim, ama temiz bir tane birazdan bu ticket'a da yüklerim.

**Comment by boratuncer** [comment]
V0.6.9b ile 573 gün için yapılan testler aşağıdadır. 13.07.2015 - 29.12.2017 tarihleri arasında net 28,516 puan kar yapıyoruz.

[#449 Yeni.xlsx](https://github.com/boratuncer/vobalgo/files/2095811/449.Yeni.xlsx)

**Comment by erkannurel** [comment]
Teşekkürler.
