### ISSUE TITLE
Eğim Üzerinde Çalışılacak

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#475]

**Comment by boratuncer** [comment]
Detay rica edebilir miyim ?

Eğim hesabını nasıl yapalım ? Kullanıcı bunu nasıl kullanacak ?

**Comment by erkannurel** [comment]
Bir kaç şekilde denemeler yapmayı düşünüyorum.

1) (Güncel Fiyat - x satır önceki fiyat) / x zamandaki satır sayısı

2) {(Günün yükseği+Günün düşüğü)/2) - Güncel fiyat} / x zamandaki satır sayısı 

3) {(x satır Günün yükseği+ x satır Günün düşüğü)/2) - Güncel fiyat} / x zamandaki satır sayısı

Denemelerde anlamlı sonuçlar çıkarılırsa ondan sonra algoritma belirlenecek. Hesaplamalarda mutlak değer veya karesini almayı düşünmüyorum. Dilersen deneyebilirsin.

**Comment by erkannurel** [comment]
Yukarıdaki üç hesaplamayı da bir kaç gün üzerinde denedim ama anlamlı sonuçlar bulamadım. Örneğin, piyasada fiyat düşerken eğim artıyor ardından fiyat yükselişe geçiyor yine eğim artıyor. Diğer bir gözlemim ise fiyat artarken eğim artıyor ama fiyat artmaya devam ederken bu sefer eğim düşüyor. Zaman konusuyla oynadım ama bir şey çıkaramadım. Ek'te incelenmek için bir dosya oluşturuldu. 

[#475 Eğim Üzerinde Çalışılacak.xlsx](https://github.com/boratuncer/vobalgo/files/2161335/475.Egim.Uzerinde.Calisilacak.xlsx)

**Comment by erkannurel** [comment]
Tekrar üzerinde çalışılmaya başlanacak. Excel'de sabit bir eğim çizilmeye çalışılacak.

**Comment by erkannurel** [comment]
#508 'de denemeler yapılmıştır. Maalesef istenilen sonuçlar alınamamıştır. Bu yüzden bu ticketı tekrar kapatıyorum.
