### ISSUE TITLE
ALTP ve SLTP günleri 3. pozisyonu açarken yeni kural

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#479]
İlk iki pozisyonda ALTP veya SLTP ile kapanmış günlerde 3. pozisyon eğer 2. pozisyon ile aynı yönlü açarsak çoğunlukla zarar ediyoruz.

Bunlar için yeni bir algoritma geliştirmek lazım.

**Comment by boratuncer** [comment]
Bir gelişme var mı ?

**Comment by erkannurel** [comment]
Üzerinde çalıştım ama bir şey bulamadım. 

"_İlk iki pozisyonda ALTP veya SLTP ile kapanmış günlerde 3. pozisyon eğer 2. pozisyon ile aynı yönlü açarsak çoğunlukla zarar ediyoruz._" dedin ALTP ile başlayan günlerin 3.pozisyon açılan günleri de incelediğimde yaklaşık 10,000 puanlık bir kazanç var.

**Comment by erkannurel** [comment]
"_İlk iki pozisyonda ALTP veya SLTP ile kapanmış günlerde 3. pozisyon eğer 2. pozisyon ile aynı yönlü açarsak çoğunlukla zarar ediyoruz._" varsayımının testi yapıldı. 

ALTP ile başlayıp üçüncü pozisyon açıldığında 41 gün var. Bu günleri incelediğimizde yukarıdaki varsayımın tam tersi gerçekleşmektedir. Aynı yöne pozisyon açtığımızda 5,950 puan kar gözükmekte. Ters  yöne pozisyon açıldığında 3,500 puan kazanılmaktadır. 

Aynı şekilde SLTP günleri incelediğimizde toplamda 9 gün var ve bu günlerde de ters veya aynı tarafa pozisyon açıldığında ciddi bir zarar gözükmemektedir. 

Sonuçları excelde inceleyebilirsin. 

[#479 ALTP ve SLTP günleri 3. pozisyonu açarken yeni kural.xlsx](https://github.com/boratuncer/vobalgo/files/2853112/479.ALTP.ve.SLTP.gunleri.3.pozisyonu.acarken.yeni.kural.xlsx)

Yukarıda yazıldığı gibi bir durum gerçekleşmediği için bu ticket'ı kapatıyorum.
