### ISSUE TITLE
Temizle Butonuna Bastıktan Sonra İletiler Penceresininde Temizlenmesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#482]
Log incelemeden sonra temizle butonuna bastığımda "Veri Listesi", "Yakalanan Sinyaller" ve "Grafik" temizleniyor ama "iletiler" penceresi temizlenmiyor. Bu pencerenin de temizlenmesini rica ediyorum.

**Comment by boratuncer** [comment]
Genelde log penceresi temizlenmez, ard arda birkaç işlem yapıldığında da log'ların halen durması beklenir. Bazı programlarda bu pencerelerin kendi temizle tuşları bile oluyor.

Ayarlar altında bir sekme yaratacağım, o seçili iken Temizle düğmesi burayı da temizleyecek hale getireceğim.

**Comment by boratuncer** [comment]
Ayarlar altında bir sekmeye bağlamadım, direk Temizle tuşu ile siliyoruz. Daha kolay oldu :)
