### ISSUE TITLE
Boş vakitlerde incelemek için grafiklerin kaydedilmesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#486]
Boş vakitlerde incelemek için grafiklerin hem telefona hem de onedrive kaydedilmesi. 02.10.2017-31.05.2018 arası eklendi.

**Comment by boratuncer** [comment]
Resimleri alırken grafik ekranı küçük boy olduğu için grafiklerde yine küçük boy olmuş.
