### ISSUE TITLE
Veri Listesi penceresinde sadeleştirme

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#489]
Veri Listesi penceresinde kullanılmayan sütunların kaldırılıması daha temiz bir görünüm sunacaktır. Örneğin Hacim ve APS sütunlarını silelim mi ?

**Comment by erkannurel** [comment]
Hacim kalsın. APS silinebilir.

**Comment by boratuncer** [comment]
İlgili değişiklik yapıldı.
