### ISSUE TITLE
İletişim pencerelerinde font boyutu güncellemesi

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#492]
Algoritmalar, Sinyaller, İletiler, Ayarlar, DDE Ham Veriler pencerelerinde font boyutu şuan 8.25pt, üst üste yazılar geldiğinde okunaklı olmuyor, 10pt'ye çıkaralım mı ?

**Comment by erkannurel** [comment]
Olur.

**Comment by boratuncer** [comment]
İlgili pencereler için fon 10 pt'ya çıkarıldı
