### ISSUE TITLE
Aktif bağlantı penceresinde toplu test sonrası sonuçlar yazdırılmıyor

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#501]
Koyu temada toplu test sonrası sonuçlar yazdırılmıyor.

![image](https://user-images.githubusercontent.com/23281592/41801868-c19abee0-7685-11e8-82d5-cc5443a0b571.png)

**Comment by boratuncer** [comment]
"Koyu temada toplu test sonrası sonuçlar yazdırılmıyor" olan konu başlığını "Aktif bağlantı penceresinde toplu test sonrası sonuçlar yazdırılmıyor" olarak değiştirdim.

**Comment by boratuncer** [comment]
Problem çözüldü.
