### ISSUE TITLE
Koruma bandı için sabit SL belirlenmesi

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#504]
Yeni geliştirilen algoritmalar yüzünden oluşabilecek zararları limitlemek adına ana TP/SL algoritmasının dışında hareket ediliyorsa zararı engelleyen bir sistem geliştirilecek.

Eğer herhangi bir algoritma yüzünden ana adaptif TP/SL yanlışlıkla iptal edilmiş ise sabit bir SL belirlenecek.

1. Pozisyon için 2000 puan, 2. Pozisyon için 1500 puan, 3. Pozisyon için 1000 puan sabit SL uygulanmasi planlanıyor.

Eğer bir algoritma yanlışlıkla adaptif TP/SL iptal etmemiş ise bu koruma bandı çalışmayacak.

**Comment by boratuncer** [comment]
Uygun dersen hemen ekleyeceğim

**Comment by erkannurel** [comment]
Olur. Olması gerekir ama aşağıda yazılan puanların testini yapmak gerekebilir. 2000 puan bana çok geldi. 

1. Pozisyon için 2000 puan, 2. Pozisyon için 1500 puan, 3. Pozisyon için 1000 puan sabit SL uygulanmasi planlanıyor.

**Comment by boratuncer** [comment]
Tüm pozisyonlar için 1500 puan olarak belirledim.  2015.07.13 ile 2018.03.30 arası tüm günlerde yapılan testlerde sonuçları değiştirmedi, hiç etkilemedi.

25.06.2018 günü için çalıştırdığımızda ise aşağıdaki sinyalleri alarak 725 puan kar ile kapattık.

Al Sinyali : 12:28:01 - #8354 - 117,525 - TP
Sat Sinyali : 10:39:20 - #3641 - 119,750 - AL
Sat Sinyali : 10:07:41 - #2102 - 119,875 - SL
Al Sinyali : 09:55:17 - #1262 - 121,375 - AL

**Comment by boratuncer** [comment]
[#504.xlsx](https://github.com/boratuncer/vobalgo/files/2134796/504.xlsx)

Test sonuçları yukarıdadır.

**Comment by boratuncer** [comment]
Kod eklendi.
