### ISSUE TITLE
#337'de güncelleme

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#508]
İlk pozisyon AL ile kapandığında, zarar kadar TP alınca pozisyonu kapatan bir algoritma ama CP ile kapanış olan günlerde ciddi kar kaçırmamıza neden oluyor.

Bunu ek bir parametre ile kontrol etmek lazım, mesela SHORT yönlü sinyalde TP aldığımız noktada Fiyat = Low ise piyasa halen aşağıya doğru gidecek demektir, TP vermeden CP'ye ilerlemek gerekebilir

**Comment by boratuncer** [comment]
Bir gelişme var mı ?

**Comment by erkannurel** [comment]
Öncelikle tek tek ALTP günler belirlenip log incelemeler yapıldı. Bu log incelemelere göre AL'dan sonra pozisyon açılıp TP aldığı süre yazıldı ve TP sonrası ilgili günlerde aynı istikamete devam mı etmiş? yoksa terse mi dönmüş o günler belirlendi.

Bu sonuçlar tekrar incelenip çözüm üretilmeye çalışılacak. 

[#508 337'de güncelleme.xlsx](https://github.com/boratuncer/vobalgo/files/2938647/508.337.de.guncelleme.xlsx)

**Comment by erkannurel** [comment]
Bugünler tek tek incelendi. Zaman algoritması koyarak birşeyler çıkarmaya çalıştım ama bulamadım. Örneğin AL'dan sonra 15 dakika içinde TP noktasına ulaştı ise +500 puan daha TP almaya devam etsin aksi takdirde TP alsın.

**Comment by erkannurel** [comment]
Şöyle bir şey denenecek: Daha önce sabit eğim üzerinde çalışmıştım #475. ALTP günlerinden sonra belli tepe ve dip noktaları oluşmakta. AL'den sonra TP noktasına geldiyse pozisyonu kapatma çizdireceğim çizgilerin tersine hareket olursa pozisyonu kapat aksi takdirde CP'ye kadar devam et gibi koşullar üzerinde çalışacağım.

**Comment by erkannurel** [comment]
Düşündüğüm gibi sabit bir eğim çizdiremedim. Bir kaç örnek excel dosyasında bulabilirsin. 

[#508 ALTP.xlsx](https://github.com/boratuncer/vobalgo/files/2954298/508.ALTP.xlsx)

**Comment by erkannurel** [comment]
ALTP günlerden sonra iki durum ile karşılaşılmakta 
Birinci durum TP aldıktan sonra aynı istikamete devam etmekte. 
İkinci durum TP aldıktan sonra ters istikamete yönelmekte. 

Ben ikinci duruma göre bir test yapacağım: AL'den sonra TP aldıysa ve x puan kadar daha aynı istikamete devam edip TP aldığı seviyenin üstüne çıktıysa terse pozisyon aç.

Terse pozisyon açıldıktan sonra x puan kadar TP al veya bu durum gerçekleşmemiş ise algoritma çalıştırarak kapat veya CP ile kapat.

**Comment by erkannurel** [comment]
İkinci durum ile ilgili testler yapıldı. Aslında sonuçlar iyi ama bu seferde aynı istikamede giden (birinci durum) günlerin bazılarını da etkiliyor. Bu yüzden bu günleri birbirinden bir kural ile ayırabilmek lazım aksi takdirde yapılan bir işe yaramayacaktır. 

[#508 337'de guncelleme.xlsx](https://github.com/boratuncer/vobalgo/files/2958555/508.337.de.guncelleme.xlsx)

**Comment by erkannurel** [comment]
Standard sapmada kullandığımız çizgilerle bir bağlantı kurup kurulamayacağı incelenecek.

**Comment by erkannurel** [comment]
İncelemeler sonucunda maalesef anlamlı bir bağlantı kurulamadı. 

Nelere bakıldı: pembe çizginin kırmızı çizgi ile kesişimlerine veya yeşil çizgi ile turkuaz çizgi kesişimlerine veya turkuaz ile kırmızı çizgilerinin arasındaki farklara veya yeşil ile pembe çizgilerin arasındaki farklara vs.

**Comment by erkannurel** [comment]
Bir süredir yukarıda çalışmalarıma rağmen çözüm üretemediğim için bu ticketi kapatıyorum.
