### ISSUE TITLE
#334 algoritmasında TP/SL şartında güncelleme

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#509]
Şuan aktif TP/SL algoritması SHORT ve LONG için tek yönlü çalışıyor;

LONG için maxofmin <= maxstddev durumdayken maxofmin >= maxstddev durumuna geçerse, yani maxofmin aşağıdan gelip maxstddev'i keserse pozisyonu kapatıyoruz.

Ama burada aynı şekilde maxofmin >= maxstddev  durumdayken maxofmin <= maxstddev olduğunda, yani maxodmin yukarıdan gelip maxstddev'i keserse de pozisyon kapatmak lazım.

Benzer şekilde SHORT için minofmax <= minstddev durumdayken minofmax >= minstddev durumuna geçerse yani minofmax aşağıdan gekip minstddev'i keserse pozisyonu kapatıyoruz.

Yine burada aynı şekilde minofmax >= minstddev durumundayken minofmax <= minstddev durumna geçerse yani minofmax yukarıdan gelip minstddev'i keserse de pozisyon kapatmak lazım.

**Comment by erkannurel** [comment]
_"LONG için Maxofmin (YEŞİL) <= maxstddev (TURKUAZ) durumdayken maxofmin (YEŞİL) >= maxstddev (TURKUAZ)  durumuna geçerse, yani maxofmin aşağıdan gelip maxstddev'i keserse pozisyonu kapatıyoruz."_ denilmiş zaten bu bizim algoritmayı kapatma kuralı. Long pozisyonu için terse olma durumunda da terse poziyon açıyoruz zaten. Örnek 31.01.2018 tarihli grafik.

![180131](https://user-images.githubusercontent.com/23281592/55586241-2a86c480-5731-11e9-9584-a08d0f083977.jpg)

_"Benzer şekilde SHORT için Yine burada aynı şekilde Minofmax (PEMBE) >= minstddev (KIRMIZI) durumundayken Minofmax (PEMBE) <= minstddev (KIRMIZI) durumna geçerse yani minofmax yukarıdan gelip minstddev'i keserse de pozisyon kapatmak lazım."_ denilmiş zaten bu bizim algoritmayı kapatma kuralı. Short pozisyonu için terse olma durumunda da terse poziyon açıyoruz zaten. Örnek 29.01.2018 tarihli grafik.

![180129](https://user-images.githubusercontent.com/23281592/55586541-e21bd680-5731-11e9-937f-a8094fd4e3fc.jpg)


Ben yazılanları yanlış mı algılıyorum lütfen kontrol edebilir misin?

**Comment by boratuncer** [comment]
Karar senin hocam
