### ISSUE TITLE
Gün sonu maillerde yazım hatası

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#516]
Gün sonu mailinde hem Yakalanan sinyallerde hem de Aracı kurum kontrat hareketlerinde yazım hatası var. Açık pozisyonumuz yoktur. Kontrol edildi.

![image](https://user-images.githubusercontent.com/23281592/42176988-91b54a5a-7e33-11e8-8372-5ffec8b4eb70.png)

**Comment by boratuncer** [comment]
Yakalanan sinyaller kısmında hata çözüldü, Aracı kurum kontrat hareketlerinde ki problem biz bilgiyi çektiğimizde InvestAZ daha kendi sistemini güncellememiş oluyor. 30sn lik bekleme koyduk, umarım bu süre içinde InvestAZ güncellemesini yapar.
