### ISSUE TITLE
MRCN Algoritmasında Pozisyon Açıldıktan sonra TP'ye Ulaşmıyorsa...

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#52]
POZİSYON AÇILDIKTAN SONRA HEDEFLENEN FİYATA GELMEDEN YENİ BİR TAHMİN GELMİŞ İSE VE AYNI YÖNDE SİNYAL GELMİŞ VE YİNE 250 PUAN VE ÜZERİ İSE DEVAM ET (BİR ÖNCEKİ POZİSYONU KAPATMA YANİ). TP'SİNİ EN SON AÇILAN POZİSYONA GÖRE REVİZE ET. 

Örneğin, 28/12/2016 tarihinde 400. satırda Long pozisyonu olarak 250 puanlık bir tahmin gerçekleşiyor ama 225'a kadar çıkıyor ve bir sonraki pakete kadar da TP alamıyoruz. Bu yüzden bir sonraki pakette Giriş Değerinden kapatıyoruz. 

Başka bir örnek daha verelim. Bu sefer TP noktamız 200 olsun. Yani 200 puan ve üstü tüm pozisyonlara girelim. Yine 28/12/2016 tarihinde 400. satırda Long pozisyonu olarak 250 puan hedefli bir pozisyon açıyoruz. 700. satıra kadar hedef gerçekleşmedi ama yine long pozisyonu ve 200 puan hedefi var o zaman sadece TP noktasımızı revize ediyoruz ve pozisyona devam ediyoruz. Eğer TP noktasına gelirse kapatsın ve bir sonraki pozisyonun açılmasını algoritma beklesin. 

Aşağıda güncel excel dosyasını bulabilirsin.

[Markov Sonuç Değerlendirme (Medyan).xlsx](https://github.com/boratuncer/vobalgo/files/682303/Markov.Sonuc.Degerlendirme.Medyan.xlsx)

**Comment by boratuncer** [comment]
Algoritma aşağıdaki şekilde değiştirildi.

Pozisyon açıldıktan sonra hedeflenen fiyata gelmeden yeni bir tahmin gelmişse;
    - Eğer yeni hedef aynı yönlü yeni bir TP ise pozisyonu kapatma
    - Diğer tüm durumlarda kapat
