### ISSUE TITLE
Pozisyon açıldıktan sonra X kadar fiyat ile TP alamadığı günler

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#521]
Pozisyon açıldıktan sonra X kadar kar edildiği halde TP almadan fiyat tekrar pozisyon açıldığı seviyeye geri gelirse pozisyonu kapat, terse aç

**Comment by erkannurel** [comment]
Telefon konuşmamıza istinaden #527 ile bu problem çözülmüştür.
