### ISSUE TITLE
ATR algoritması eklenecek

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#529]
ATR algoritması toplu testler arasına eklenecek, gün sayısını kişi menüden girebilmesi gerekiyor.

**Comment by boratuncer** [comment]
Algorritma eklendi, fakat sonuçlar istediğimiz gibi değil. 15 günlük ve 30 günlük ATR sonuçlarını örnek olarak ekte koydum.

VIOP piyasamız için 2000 puanlar seviyesinde seyrediyor, bazen 3000 puanlara çıktığı oluyor. Bu çok büyük sorun çünkü seminerde anlatılan 2.5 kat ile TP, 1 kat ile SL almak.

[ATR Sonuçları.xlsx](https://github.com/boratuncer/vobalgo/files/2779607/ATR.Sonuclari.xlsx)

Matrix'ten veya başka bir yerden bulduğumuz bu sonuçları teyit etme şansımız var mı ?

**Comment by erkannurel** [comment]
Matrikten ATR sonuçlarını aşağıdaki print screenda paylaşıyorum. Yukarıda ve telefonda söylediğin sonuçlara yakın çıkıyor şuanda.

![image](https://user-images.githubusercontent.com/23281592/51520698-76fe7b80-1e35-11e9-8932-7d2148e84968.png)

**Comment by boratuncer** [comment]
Başka bir algoritması var mı ?

Yoksa ticket'ı kapatacağım.

**Comment by boratuncer** [comment]
Yanlışlıkla reopen yapıldı.
