### ISSUE TITLE
2019 kontrat isimleri sisteme girilecek

### ISSUE THREAD

**Issue by boratuncer** [boratuncer/vobalgo#530]
2019 kontrat isimlerini aşağıdaki formatta rica edebilir miyiz ?

    <DNCItem>
      <sdate>01/11/18</sdate>
      <edate>31/12/18</edate>
      <contract>F_XU0301218</contract>
    </DNCItem>

**Comment by erkannurel** [comment]
<DNCItem>
      <sdate>01/01/19</sdate>
      <edate>28/02/19</edate>
      <contract>F_XU0300219</contract>
</DNCItem>
<DNCItem>
      <sdate>01/03/19</sdate>
      <edate>30/04/19</edate>
      <contract>F_XU0300419</contract>
</DNCItem>
<DNCItem>
      <sdate>01/05/19</sdate>
      <edate>30/06/19</edate>
      <contract>F_XU0300619</contract>
    </DNCItem>
<DNCItem>
      <sdate>01/07/19</sdate>
      <edate>31/08/19</edate>
      <contract>F_XU0300819</contract>
</DNCItem>
<DNCItem>
      <sdate>01/09/19</sdate>
      <edate>31/10/19</edate>
      <contract>F_XU0301019</contract>
</DNCItem>
<DNCItem>
      <sdate>01/11/19</sdate>
      <edate>31/12/19</edate>
      <contract>F_XU0301219</contract>
</DNCItem>
