### ISSUE TITLE
Belli Alış ve Satışların Ortalaması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#532]
Örneğin, 100 kontrat ve üstü işlemlerin alış ise ortalamasını (Basit, Ağırlıklı olabilir) al veya 100 kontrat ve üstü işlemlerin satış ise ortalamasını (Basit, Ağırlıklı olabilir) al. Bu iki ortalamayı birbiri ile karşılaştır.

**Comment by boratuncer** [comment]
Merhabalar,

Milestone V0.7.3 olarak işaretlenmiş, bu sürümü 01.02.2019 da vereceğiz, konuyu bu zaman kadar çözebilecek mi ? Eğer çözülemeyecekse bir sonraki versiyonlardan biri hedeflenebilir. 

Ayrıca konu "task" veya "question" hangisi olacak ?

"task" label'ını bir versiyonda eklenmesi istenilen özellikler için kullanıyoruz. "question" label'ını da daha uzun sürede test edilecek, performansı beğenilirse koda eklenmesi için "task" label'ına geçirilecek işler için kullanmak gerekiyor.

Yani daha koda eklenecek seviyede değilse "question" olarak kalsın, koda ekleyeceğimiz zaman bunu "task" yapalım.

Birde konu başlığında "Algo Denemesi" yazmaya gerek yok, zaten label'da "algo" atanmış.

İyi çalışmalar,
Bora

**Comment by erkannurel** [comment]
Bir aylık inceleme sonucunda arzu edilen sonuca ulaşılamadı. Örnek günler ek'tedir. 

[#532-1.xlsx](https://github.com/boratuncer/vobalgo/files/3174620/532-1.xlsx)

[#532-2.xlsx](https://github.com/boratuncer/vobalgo/files/3174633/532-2.xlsx)
