### ISSUE TITLE
Sapma Payının Minumum Seviyeye Çekilmesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#533]
Yapılan uzun vadeli testlerde sapma payının çok yüksek olduğu görülmektedir. Testler haricinde de gerçek trade de bize büyük kayıplar yaşattığını gördük. Bir pozisyon açtığımızda kabaca 50 puan hedefimizin altına düşmekteyiz. Son yapılan testlerde yaklaşık olarak 80,000 puan kaybettiğimiz gözükmekte. Algoritma ne olursa olsun bunun düzeltilmesi gerekmektedir. Bunu daha önce de konusu açmıştım. Test sonuçları aşağıdadır. 

[28.12.2018_Toplu Test.xlsx](https://github.com/boratuncer/vobalgo/files/2789157/28.12.2018_Toplu.Test.xlsx)

**Comment by boratuncer** [comment]
Bunu nasıl yapacağız ? Teknik bir formül var mı ?

**Comment by boratuncer** [comment]
Merhabalar,

Milestone V0.7.3 olarak işaretlenmiş, bu sürümü 01.02.2019 da vereceğiz, konuyu bu zaman kadar çözebilecek mi ? Eğer çözülemeyecekse bir sonraki versiyonlardan biri hedeflenebilir.

Ayrıca konu "task" veya "question" hangisi olacak ?

"task" label'ını bir versiyonda eklenmesi istenilen özellikler için kullanıyoruz. "question" label'ını da daha uzun sürede test edilecek, performansı beğenilirse koda eklenmesi için "task" label'ına geçirilecek işler için kullanmak gerekiyor.

Yani daha koda eklenecek seviyede değilse "question" olarak kalsın, koda ekleyeceğimiz zaman bunu "task" yapalım.

İyi çalışmalar,
Bora

**Comment by erkannurel** [comment]
Emir tipini değiştirerek yapabilir. Biz piyasa emri (PYS) gönderiyoruz. Bunun yerine şartlı emir göndermemiz gerekecek. Aşağıdaki linkte emir tiplerini görebilirsin. Sanırım burada LMT emir tipini kullanmak gerekecek. 

http://www.borsaistanbul.com/urunler-ve-piyasalar/piyasalar/vadeli-islem-ve-opsiyon-piyasasi/emirler

**Comment by boratuncer** [comment]
Biz ne zaman emir göndereceğimizi bilmiyoruz. Pozisyon açarkende, pozisyonu kapatırken de adaptif bir algoritma çalışıyor.

Sabit TP/SL kullanırsak en azından pozisyonu kapatacağımız emirleri LMT yapabiliriz ama onun dışında bunu kullanamayız.

Bir yol görüyor musun ?

**Comment by erkannurel** [comment]
Şuan için görmüyorum bu yüzden şimdilik ticketı kapatıyorum.
