### ISSUE TITLE
Hull Moving Average'ı Araştır

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#534]
Araştırma sıralarında karşıma çıkan bir hareketli ortalama çeşidi. Lag'in en az olduğu ve fiyatlara en yakın hareket ettiği idda ediliyor. Belki uzun ve kısa vadeli bakarak (kesiştirerek) bir trigger ortaya çıkarabiliriz. 

https://www.fidelity.com/learning-center/trading-investing/technical-analysis/technical-indicator-guide/hull-moving-average

**Comment by boratuncer** [comment]
Merhabalar,

Milestone V0.7.3 olarak işaretlenmiş, bu sürümü 01.02.2019 da vereceğiz, konuyu bu zaman kadar çözebilecek mi ? Eğer çözülemeyecekse bir sonraki versiyonlardan biri hedeflenebilir. 

Ayrıca konu "task" veya "question" hangisi olacak ?

"task" label'ını bir versiyonda eklenmesi istenilen özellikler için kullanıyoruz. "question" label'ını da daha uzun sürede test edilecek, performansı beğenilirse koda eklenmesi için "task" label'ına geçirilecek işler için kullanmak gerekiyor.

Yani daha koda eklenecek seviyede değilse "question" olarak kalsın, koda ekleyeceğimiz zaman bunu "task" yapalım.

Birde konu başlığında "Algo Denemesi" yazmaya gerek yok, zaten label'da "algo" atanmış.

İyi çalışmalar,
Bora

**Comment by erkannurel** [comment]
Tick'lik data olmasından dolayı çok volatilite'li gözüküyor. Hem sıra olarak hem hacim olarak ağırlandırılmıştır ama bir sonuca varılamamıştır. 

[#534.xlsx](https://github.com/boratuncer/vobalgo/files/3103351/534.xlsx)

![image](https://user-images.githubusercontent.com/23281592/56500489-beb7a080-6513-11e9-91ec-4fa226414995.png)
