### ISSUE TITLE
10000. satırda sinyal veren 10400'de kapanıyor.

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#58]
![bug 1](https://cloud.githubusercontent.com/assets/23281592/21840045/ce3824d6-d7e3-11e6-9053-8a81e7b20f67.jpg)

**Comment by boratuncer** [comment]
Kodda şöyle bir değilşiklik yapıldı.

- 1100'de açmışsa TP / SL paketin içinde nerede gelirse kapatıyor
- 1500'de halen kapanmamışsa ya AL ile kapatıyor, ya da pozisyona açık devam ediyor
