### ISSUE TITLE
Ayarlar Menüsündeki Rutin Ayarların Açılışta Gelmesi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#66]
Ayarlar Menüsündeki Rutin Ayarların Açılışta Gelse iyi olur. Setting dosyasını yüklenmesine izin vermediği için buraya yükleyemedim. 

1) Kişisel Ayarlarda 3 seçenekte seçili durumda olacak ve saat 18:14:59 olacak. 

2) Bağlantı >DDE Ayarlarında "Kapanışta en son T. hacim değerini kayıt et" seçili olacak. 

3) Bağlantı > Mail ayarlarında "Yukarıdaki erişim bilgilerini kullanarak mail gönder" seçeneği seçili olacak.

**Comment by boratuncer** [comment]
V0.5.5 te çoğul settings.xml uygulamasına geçildi.
