### ISSUE TITLE
Markov çıkarma işareti bölüm yaparsak ne olur?

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#67]
Bir sorum olacak ek'teki excel dosyasına bakarsan bana daha önce Markov'daki problemi rakamlar ile göstermistin. Bana iki çıkan rakamın farklı olduğunu kanıtlamamı sormuştun. Bende eksi(-) yerine bölüm (/) işareti yaptığımda iki tabloda rakamların farklı olduğunu kanıtlayabiliyorum. Rica etsem inceler misin?

[Markov Problem.xlsx](https://github.com/boratuncer/vobalgo/files/724067/Markov.Problem.xlsx)

**Comment by boratuncer** [comment]
Performans üzerinde değişiklik göstermedi.
