### ISSUE TITLE
Ayarlar penceresinde menünün açık kalması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#68]
Ayarlar penceresine girdiğimizde (+) olanların (-) olarak gelmesi kullanıcının daha kolay ve hızlı işlem yapmasını sağlayacaktır. 
![untitled](https://cloud.githubusercontent.com/assets/23281592/22287712/7ceb5e12-e2fc-11e6-8acc-89caabd13daf.jpg)

**Comment by boratuncer** [comment]
Genel kullanıma aykırı, piyasada ki hemen tüm programlar benzer şekilde kullanıyor.

**Comment by boratuncer** [comment]
Genel kullanımı hızlandıracağı için tekrar gözden geçirilecek

**Comment by boratuncer** [comment]
İlgili özellik eklendi.
