### ISSUE TITLE
Algoritmalar kısmından MRCN algoritmasını eklediğimizde anasayfada çıkmama problemi

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#72]
Algoritmalara geldiğimde MRCN algoritmasına kar alımı 0,25 - zarar kap. 0,50 yapıp ekledikten sonra kapatıp ana sayfaya geldiğimde MRCN algoritmasını log inceleme için seçemiyorum. 

![image](https://cloud.githubusercontent.com/assets/23281592/22626397/0eaf2124-ebb5-11e6-854b-37711faaadf1.png)

**Comment by boratuncer** [comment]
Problem V0.5.6 da çözüldü
