### ISSUE TITLE
Hareketli Yüksek ve Düşük Grafik Çizdirme

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#73]
Fiyatın 300 ticklik hareketli olarak Max ve Min rakamlarını alıyoruz. Sonrasında grafikte fiyat, bulduğumuz yeni max ve min rakamlarını çizdiriyoruz. Aşağıda bir excel örneği var. 

Bunu log inceleme yaptığımızda grafikte görmek istiyorum. VIHL algoritmasının koyduğu mavi noktalarda olursa sevinirim. 

Aşağıdaki excel örneğinde 300 hareketli max ve min rakamları kullanılmıştır. 300'ü parametrik yapabilirsen daha çok test fırsatımız olur. Bu aşamada yapılmazsada sorun değil.  

[LOW-HIGH.xlsx](https://github.com/boratuncer/vobalgo/files/772378/LOW-HIGH.xlsx)

**Not: adaptif TP ve SL ile ilgili bir çalışmadır. Acil olarak yapabilirsen çok sevinirim.**

**Comment by boratuncer** [comment]
Özellik eklendi.
