### ISSUE TITLE
Bistech Viop Faz 2 Değişiklikleri

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#75]
Bistech Viop geçişi ile ilgili yapılacakları okuyup araştırdığım kadarıyla bizi ilgilendiren en önemli gelişme kontrat isimlerinin değişecek olmasıdır. Örneğin, şuan F_XU0300417S0 kontrat ismini kullanıyoruz "S0" kaldırılacak ve yerine F_XU0300417 adlı kontrat ismi gelecektir (6 Mart başlangıç). 

Diğer yapılacak değişiklikler şuan için bizi ilgilendirdiğini düşünmüyorum ama yinede öğrenmen için ek'te bir döküman ekledim. 

[VİOP bistech değişikliği Matriks.pdf](https://github.com/boratuncer/vobalgo/files/815077/VIOP.bistech.degisikligi.Matriks.pdf)

**Comment by boratuncer** [comment]
DNC class aşağıdaki şekilde değiştirildi.

    <DNCItem>
      <sdate>01/03/17</sdate>
      <edate>05/03/17</edate>
      <contract>F_XU0300417S0</contract>
    </DNCItem>
    <DNCItem>
      <sdate>06/03/17</sdate>
      <edate>29/04/17</edate>
      <contract>F_XU0300417S0</contract>
    </DNCItem>    
    <DNCItem>
      <sdate>01/05/17</sdate>
      <edate>30/06/17</edate>
      <contract>F_XU0300617S0</contract>
    </DNCItem>
    <DNCItem>
      <sdate>01/07/17</sdate>
      <edate>31/08/17</edate>
      <contract>F_XU0300817S0</contract>
    </DNCItem>
    <DNCItem>
      <sdate>01/09/17</sdate>
      <edate>31/10/17</edate>
      <contract>F_XU0301017S0</contract>
    </DNCItem>
    <DNCItem>
      <sdate>01/11/17</sdate>
      <edate>31/12/17</edate>
      <contract>F_XU0301217S0</contract>
    </DNCItem>
