### ISSUE TITLE
Toplu testlerde 6 Mart itibariyle sonuçların sıfır çıkması

### ISSUE THREAD

**Issue by erkannurel** [boratuncer/vobalgo#83]
6 Mart 2017 tarihinde "F_XU0300417S0" kontratı isim değişikliğine uğradığı için toplu testlerde sonuç sıfır çıkmaktadır. Yeni kontrat ismi "F_XU0300417" Bu hatanın düzeltilmesini rica ederim.

Not: Bundan sonra gelecek kontratların isimlerinde de "S0" ibaresi olmayacaktır. Örneğin bir sonraki ayda "F_XU0300617" haziran kontratı işlem görecektir. 

![bug](https://cloud.githubusercontent.com/assets/23281592/24140769/3adc9a98-0e32-11e7-8364-86ddb59dd897.jpg)

**Comment by boratuncer** [comment]
Problem çözüldü.
